#!/usr/bin/env node
/**
 * Emits src/server/tools/_generated-tags.ts from the built catalog so
 * KNOWN_COMPONENTS is derived from component source, not maintained by hand.
 * Runs as part of `build:catalog`; the output IS committed (fresh checkouts
 * must type-check without a build).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const here = import.meta.dirname ?? '.';
const catalogPath = resolve(here, '../catalog/catalog.json');
const outPath = resolve(here, '../server/tools/_generated-tags.ts');

const catalog = JSON.parse(readFileSync(catalogPath, 'utf8')) as {
  components: Array<{ tag: string }>;
};
const tags = catalog.components.map((c) => c.tag).sort();

const body = `/**
 * GENERATED by src/scripts/generate-known-tags.ts from catalog.json.
 * Do not edit by hand — run \`pnpm build:catalog\`.
 */
export const KNOWN_COMPONENTS: readonly string[] = [
${tags.map((t) => `  '${t}',`).join('\n')}
];
`;

writeFileSync(outPath, body);
console.log(`Wrote ${tags.length} tags to ${outPath}`);
