/**
 * MISATTRIBUTION OF MEMORY
 *
 * Attributing a memory to the wrong source, or confusing
 * imagined events with real ones.
 */

import type { BiasCard } from '../core/types.js';
import {
  BiasCategory,
  ImpactLevel,
} from '../core/types.js';

export const misattributionMemory: BiasCard = {
  //===========================================
  // METADATA
  //===========================================
  metadata: {
    id: 'misattribution-memory',
    name: 'Misattribution of Memory',
    aliases: ['Source Confusion', 'Cryptomnesia', 'Source Monitoring Error'],
    category: BiasCategory.MEMORY,
    relatedCategories: [
      BiasCategory.DECISION_MAKING,
      BiasCategory.PERCEPTION,
    ],
    tags: [
      'memory',
      'attribution',
      'source-confusion',
      'content-provenance',
      'version-tracking',
      'ai-content',
    ],
  },

  //===========================================
  // DEFINITION
  //===========================================
  definition: {
    simple:
      'We attribute memories to the wrong source or confuse imagined events with real ones.',

    detailed: `Misattribution of memory occurs when a person correctly remembers information but incorrectly recalls its source, or when imagined, suggested, or fabricated events are remembered as having actually happened. This is one of Daniel Schacter's "Seven Sins of Memory."

There are three major forms: (1) source misattribution, where a memory is attributed to the wrong origin (e.g., confusing something read online with something a friend said); (2) cryptomnesia, where a person believes they have produced an original idea when they have actually encountered it before; and (3) false memory, where suggestion or imagination creates memories of events that never occurred.

In UX design, misattribution is critical for content-heavy platforms where users encounter information from multiple sources. Without clear attribution, users confuse who said what, which version of a document is authoritative, and whether content was generated by a human or by AI. Clear provenance, version tracking, and source labeling are essential countermeasures.`,

    psychologyBasis: {
      discoveredBy: 'Daniel Schacter',
      year: 1999,
      theory: 'Seven Sins of Memory',
      mechanism: `Memory encoding stores content and source information through partially independent processes. Misattribution occurs because:

1. **Source-Content Dissociation**: The brain stores "what happened" separately from "where I learned it," and the source trace decays faster than the content trace
2. **Familiarity Without Recollection**: Information can feel familiar without activating the contextual details of when or where it was encountered
3. **Imagination Inflation**: Vividly imagining an event can create memory traces indistinguishable from traces of real experiences
4. **Schema-Driven Reconstruction**: When retrieving memories, the brain fills in missing source details using plausible guesses based on schemas and expectations
5. **Gist Extraction**: Over time, memories lose specific details and retain only the gist, making source identification increasingly unreliable`,
    },

    realWorldExample: `In a classic study, participants read facts from various sources and later attributed those facts to incorrect sources at high rates. In daily life, people regularly misremember where they heard a piece of news — confusing a tweet with a news article, a friend's opinion with their own idea, or AI-generated text with something a colleague wrote. This has become especially acute in the age of social media resharing and AI-generated content.`,
  },

  //===========================================
  // DESIGN IMPACT
  //===========================================
  designImpact: {
    description: `Misattribution of memory affects how users track the origin and authorship of content, distinguish between versions, and evaluate the trustworthiness of information. Designers must:

- Provide persistent, clear source labels so users can identify content origin
- Distinguish original content from shared, forwarded, or reshared content
- Track and surface activity attribution so users know who did what
- Maintain version history with clear authorship and timestamps
- Clearly label AI-generated vs human-authored content`,

    whenToUse: [
      {
        title: 'Content Sourcing and Attribution',
        scenario:
          'When displaying content that originates from multiple sources or authors',
        example:
          'Show a persistent "Source: @author" label and timestamp on every piece of content, even after resharing or embedding',
        impact: ImpactLevel.CRITICAL,
      },
      {
        title: 'Shared and Forwarded Content',
        scenario:
          'When content is reshared, forwarded, or reposted across users or channels',
        example:
          'Display a clear "Shared from [Original Author]" label with a link to the original, distinguishing the sharer from the creator',
        impact: ImpactLevel.HIGH,
      },
      {
        title: 'Activity Attribution in Collaborative Tools',
        scenario:
          'When multiple users contribute to a shared document, project, or conversation',
        example:
          'Show inline avatars and names next to each edit, comment, or action in a shared workspace',
        impact: ImpactLevel.HIGH,
      },
      {
        title: 'Version History and Change Tracking',
        scenario:
          'When documents, designs, or data evolve through multiple revisions',
        example:
          'Provide a version timeline showing who changed what and when, with the ability to diff between versions',
        impact: ImpactLevel.HIGH,
      },
      {
        title: 'AI-Generated Content Labeling',
        scenario:
          'When AI produces, assists with, or modifies content in user-facing flows',
        example:
          'Add a visible "Generated by AI" badge with a tooltip explaining the AI\'s role and any human review that occurred',
        impact: ImpactLevel.CRITICAL,
      },
    ],

    whenToAvoid: [
      {
        title: 'Overwhelming Attribution Noise',
        reason:
          'Excessive source labels on every micro-interaction can create cognitive overload',
        consequence:
          'Users ignore all attribution labels, defeating the purpose entirely',
        alternative:
          'Use progressive disclosure: show primary source inline, and detailed provenance on demand',
      },
      {
        title: 'Privacy-Sensitive Contexts',
        reason:
          'Revealing the exact source of anonymous or confidential contributions may violate privacy',
        consequence:
          'Users stop contributing for fear of identification',
        alternative:
          'Attribute to roles or teams ("Edited by a reviewer") rather than individuals when anonymity is needed',
      },
      {
        title: 'Trivial Content Changes',
        reason:
          'Tracking authorship of minor formatting or typo fixes adds noise without value',
        consequence:
          'Version history becomes unusable when cluttered with trivial changes',
        alternative:
          'Aggregate minor edits and only surface substantive content changes with full attribution',
      },
      {
        title: 'Real-Time Collaborative Editing',
        reason:
          'Showing constant attribution during live co-editing is distracting',
        consequence:
          'Users focus on who typed what instead of the content itself',
        alternative:
          'Show collaborator cursors in real time but defer detailed attribution to version history',
      },
    ],

    commonMistakes: [
      {
        title: 'Losing Attribution on Reshare',
        description:
          'When content is shared or forwarded, the original author label is dropped, showing only the sharer',
        why: 'Users then attribute the content to the person who shared it, not the person who created it',
        fix: 'Maintain a chain of attribution: "Created by X, shared by Y" persists through all forwards',
      },
      {
        title: 'No AI Content Distinction',
        description:
          'AI-generated summaries, suggestions, or drafts are displayed identically to human-authored content',
        why: 'Users cannot distinguish machine output from human work, leading to false trust or false credit',
        fix: 'Use a consistent visual indicator (badge, icon, or border treatment) for all AI-generated content',
      },
      {
        title: 'Ambiguous Version Ownership',
        description:
          'Version history shows timestamps but not who made each change',
        why: 'Users cannot determine who introduced a specific change, making accountability impossible',
        fix: 'Always pair version entries with author identity: avatar + name + timestamp + change summary',
      },
      {
        title: 'Blending Quotes with Commentary',
        description:
          'Inline quotes from other users are styled identically to the author\'s own commentary',
        why: 'Readers misattribute quoted opinions to the person presenting them',
        fix: 'Use distinct visual treatment for quotes (indentation, border, quotation marks, source link)',
      },
    ],

    impactAreas: {
      layout: {
        level: ImpactLevel.HIGH,
        description:
          'Layout determines where attribution information appears and how persistently it is visible',
        examples: [
          'Bylines placed above content are noticed; bylines buried at the bottom are missed',
          'Inline attribution (next to the content) is more effective than separated attribution',
          'Sticky headers can maintain source context as users scroll through long content',
          'Card-based layouts should include source labels on every card, not just the feed header',
        ],
      },
      typography: {
        level: ImpactLevel.MEDIUM,
        description:
          'Typographic differentiation helps users distinguish content from different sources',
        examples: [
          'Quoted text in a distinct font or style prevents misattribution of others\' words',
          'Author names in a consistent, recognizable weight aid source tracking',
          'AI-generated content in a subtly different typeface or with a label signals non-human origin',
          'Timestamps in a secondary type style provide temporal context without competing with content',
        ],
      },
      color: {
        level: ImpactLevel.HIGH,
        description:
          'Color coding can signal content origin and authorship at a glance',
        examples: [
          'Unique color accents per contributor in collaborative documents aid attribution',
          'AI-generated content with a distinct background tint separates it from human content',
          'Shared/forwarded content with a subtle border color distinguishes it from original posts',
          'Version diff highlighting uses color to show who added or removed text',
        ],
      },
      interaction: {
        level: ImpactLevel.HIGH,
        description:
          'Interactions should reinforce source awareness rather than obscure it',
        examples: [
          'Hovering over content reveals full provenance: author, date, edit history',
          'Clicking a "source" link navigates to the original content in context',
          'Copy/paste operations should carry attribution metadata when possible',
          'Sharing workflows should prompt users to verify or add attribution',
        ],
      },
      content: {
        level: ImpactLevel.CRITICAL,
        description:
          'Content strategy must prioritize clear provenance to prevent source confusion',
        examples: [
          'Every article, post, or message should have a visible author and timestamp',
          'AI-generated summaries should state "This summary was generated by AI based on [source]"',
          'Curated content should distinguish the curator from the original authors',
          'User-generated vs editorial content should be visually distinct',
        ],
      },
      accessibility: {
        level: ImpactLevel.HIGH,
        description:
          'Attribution must be available to all users regardless of how they access the interface',
        examples: [
          'Screen readers must announce content source before or after reading content',
          'ARIA labels on attribution elements should include author and date',
          'Color-coded authorship must have non-color alternatives (icons, labels, patterns)',
          'Keyboard navigation should allow users to query the source of any content block',
        ],
      },
    },
  },

  //===========================================
  // EXAMPLES
  //===========================================
  examples: {
    good: [
      {
        title: 'Clear "Shared From" Labels',
        description:
          'Social media platform showing persistent original author attribution when content is reshared',
        code: `<article class="shared-post">
  <header class="share-context">
    <img src="sharer-avatar.jpg" alt="Maria Lopez">
    <div class="share-meta">
      <span class="sharer">Maria Lopez shared this</span>
      <time datetime="2026-03-18">2 days ago</time>
    </div>
  </header>
  <div class="original-content" aria-label="Originally posted by David Kim">
    <header class="original-author">
      <img src="author-avatar.jpg" alt="David Kim">
      <div class="author-meta">
        <span class="author-name">David Kim</span>
        <span class="badge original">Original Author</span>
        <time datetime="2026-03-10">Mar 10, 2026</time>
      </div>
    </header>
    <p>Here's what I learned from our latest user research sprint...</p>
  </div>
</article>`,
        explanation:
          'The sharer (Maria) and the original author (David) are both clearly identified. The "Original Author" badge prevents users from attributing the content to the person who merely shared it.',
        principle:
          'Persistent chain-of-attribution prevents source confusion on reshared content',
        metrics: {
          before: '62% of users attributed reshared content to the sharer, not the author',
          after: '11% misattributed after adding clear "Original Author" labels',
          improvement: '82% reduction in source misattribution',
        },
      },
      {
        title: 'Version History with Author Attribution',
        description:
          'Document editor showing who made each change with timestamps and diffs',
        code: `<section class="version-history" aria-label="Document version history">
  <h3>Version History</h3>
  <ol class="version-timeline" reversed>
    <li class="version current">
      <div class="version-header">
        <img src="avatar-sarah.jpg" alt="">
        <span class="author">Sarah Chen</span>
        <time datetime="2026-03-19T14:30:00Z">Today, 2:30 PM</time>
        <span class="badge current">Current</span>
      </div>
      <p class="change-summary">Updated pricing section, added competitor analysis</p>
      <button class="text-button">View changes</button>
    </li>
    <li class="version">
      <div class="version-header">
        <img src="avatar-james.jpg" alt="">
        <span class="author">James Park</span>
        <time datetime="2026-03-18T09:15:00Z">Yesterday, 9:15 AM</time>
      </div>
      <p class="change-summary">Initial draft of market overview</p>
      <button class="text-button">View changes</button>
    </li>
    <li class="version ai-generated">
      <div class="version-header">
        <span class="ai-icon" aria-hidden="true"></span>
        <span class="author">AI Assistant</span>
        <span class="badge ai">AI-Generated</span>
        <time datetime="2026-03-17T16:00:00Z">Mar 17, 4:00 PM</time>
      </div>
      <p class="change-summary">Generated outline from meeting transcript</p>
      <span class="review-status">Reviewed by James Park</span>
      <button class="text-button">View changes</button>
    </li>
  </ol>
</section>`,
        explanation:
          'Each version entry shows who made the change, when, and what changed. AI-generated contributions are distinctly labeled with a badge and show who reviewed the output. Users can always trace any sentence to its author.',
        principle:
          'Detailed version attribution prevents confusion about who introduced specific content',
      },
      {
        title: 'AI-Generated vs Human Content Distinction',
        description:
          'Interface clearly distinguishing AI-generated content from human-authored content',
        code: `<div class="content-feed">
  <article class="content-block human">
    <header>
      <img src="analyst-avatar.jpg" alt="">
      <span class="author">Priya Sharma, Senior Analyst</span>
      <time>Mar 19, 2026</time>
    </header>
    <p>Based on Q1 results, I recommend we focus expansion on
    the APAC region where we saw 34% growth.</p>
  </article>

  <article class="content-block ai-generated" aria-label="AI-generated summary">
    <header>
      <span class="ai-badge" role="img" aria-label="AI generated">AI</span>
      <span class="label">AI Summary</span>
      <span class="source-note">Based on 12 analyst reports from Q1 2026</span>
    </header>
    <p>Key themes across analyst reports: APAC growth (mentioned 9x),
    supply chain risk (7x), pricing pressure in EU (5x).</p>
    <footer class="provenance">
      <button class="text-button">View source reports</button>
      <span class="disclaimer">AI-generated summary. Verify against source documents.</span>
    </footer>
  </article>
</div>`,
        explanation:
          'Human content shows the author\'s name, role, and photo. AI-generated content has a distinct badge, states its sources, and includes a verification disclaimer. Users cannot confuse the two.',
        principle:
          'Distinct visual treatment for AI content prevents false attribution to human authors',
      },
    ],

    bad: [
      {
        title: 'Reshared Content Without Attribution',
        description:
          'Content shared without indicating the original author, causing users to attribute it to the sharer',
        code: `<!-- DON'T DO THIS -->
<article class="post">
  <header>
    <img src="maria-avatar.jpg" alt="Maria Lopez">
    <span class="name">Maria Lopez</span>
    <time>2 hours ago</time>
  </header>
  <p>Here's what I learned from our latest user research sprint...</p>
  <!-- No indication that Maria shared this, not wrote it.
       The original author (David Kim) is invisible. -->
</article>`,
        explanation:
          'Maria shared David\'s content but the interface presents it as if Maria wrote it. Users will attribute these insights to Maria, not David. The original author receives no credit and users form incorrect mental models of who has expertise.',
        principle:
          'Dropping attribution on reshare causes systematic source misattribution',
      },
      {
        title: 'AI Content Disguised as Human Content',
        description:
          'AI-generated text presented without any label, indistinguishable from human-written content',
        code: `<!-- DON'T DO THIS -->
<div class="report">
  <h3>Q1 Market Analysis</h3>
  <p>The APAC region showed 34% growth driven by enterprise
  adoption. We recommend focusing expansion efforts here.</p>
  <!-- This was entirely AI-generated from raw data, but
       nothing indicates that. Users assume a human analyst
       wrote it, trusting it differently than they should. -->
</div>`,
        explanation:
          'AI-generated analysis is presented as if authored by a human analyst. Users may trust it differently, cite it as expert opinion, or give credit to a human who did not write it. This is a direct misattribution risk.',
        principle:
          'Unlabeled AI content creates false trust and incorrect credit attribution',
      },
      {
        title: 'Version History Without Authors',
        description:
          'Document versions showing only timestamps with no authorship information',
        code: `<!-- DON'T DO THIS -->
<div class="versions">
  <h4>Document History</h4>
  <ul>
    <li>Version 3 - Modified Mar 19, 2:30 PM</li>
    <li>Version 2 - Modified Mar 18, 9:15 AM</li>
    <li>Version 1 - Created Mar 17, 4:00 PM</li>
  </ul>
</div>`,
        explanation:
          'Without author names, users cannot determine who made which changes. In a team setting, this makes it impossible to ask the right person about a change, and users may misattribute decisions to the wrong colleague.',
        principle:
          'Timestamps without authorship make source tracking impossible in collaborative work',
      },
    ],

    realWorld: [
      {
        company: 'Twitter/X',
        product: 'Retweet Attribution',
        description: 'Twitter\'s retweet format clearly shows "User retweeted" above the original post, preserving the original author\'s name, avatar, and timestamp. However, quote tweets can blur the line between the quoter\'s commentary and the original content.',
        effectiveness: 'effective',
        analysis: 'The retweet mechanism mostly prevents misattribution by preserving full original context. Quote tweets are less effective because the quoter\'s framing can override the reader\'s perception of authorship and intent.',
      },
      {
        company: 'Google Docs',
        product: 'Suggesting Mode and Version History',
        description: 'Google Docs attributes every edit, suggestion, and comment to a specific user with colored highlighting per author. Version history shows who changed what and when, with the ability to restore any version.',
        effectiveness: 'very-effective',
        analysis: 'Per-author color coding and detailed version history make attribution nearly error-proof in collaborative editing. Users can always trace any sentence back to its author.',
      },
      {
        company: 'OpenAI',
        product: 'ChatGPT Content Labeling',
        description: 'ChatGPT conversations clearly label user messages vs AI responses with distinct visual treatments. However, when users copy AI-generated text into other contexts (documents, emails), the AI attribution is lost.',
        effectiveness: 'effective',
        analysis: 'In-app attribution is strong, but the design does not solve for downstream misattribution when AI content is copied elsewhere. This is a significant gap in the attribution chain.',
      },
      {
        company: 'Wikipedia',
        product: 'Edit History and Talk Pages',
        description: 'Every Wikipedia edit is attributed to a user or IP address with a timestamp. The "View history" tab shows the complete provenance of every sentence. Talk pages capture the reasoning behind editorial decisions.',
        effectiveness: 'very-effective',
        analysis: 'Wikipedia\'s edit history is one of the most thorough attribution systems on the web. Users can trace any claim to the exact edit and editor who introduced it, which is essential for an encyclopedia.',
      },
    ],

    abTests: [
      {
        title: 'Shared Content: With vs Without Original Author Label',
        hypothesis:
          'Adding a clear "Originally by [Author]" label will reduce source misattribution on reshared content',
        controlVersion: {
          description:
            'Reshared posts show only the sharer\'s name and avatar, with no indication of the original author',
          metrics: {
            conversionRate: 'N/A',
            misattributionRate: '62%',
            trustScore: '6.2/10',
          },
        },
        treatmentVersion: {
          description:
            'Reshared posts show both the sharer and the original author with a clear "Originally posted by [Author]" label and link to original',
          metrics: {
            conversionRate: 'N/A',
            misattributionRate: '11%',
            trustScore: '8.1/10',
          },
        },
        results: {
          winner: 'treatment',
          analysis:
            'Source misattribution dropped from 62% to 11% with clear original author labels. Trust scores increased by 31% as users felt more confident about content provenance. Engagement with original authors also increased.',
          learnings: [
            'Persistent attribution labels are the most effective countermeasure to source confusion',
            'Users actively appreciate knowing the true source of content',
            'Trust in the platform increased when attribution was transparent',
            'Original authors received more followers and engagement when properly credited',
          ],
        },
      },
      {
        title: 'AI Content: Labeled vs Unlabeled',
        hypothesis:
          'Labeling AI-generated content will change how users evaluate and trust it',
        controlVersion: {
          description:
            'AI-generated report summaries displayed with no AI indicator, identical styling to human-authored summaries',
          metrics: {
            conversionRate: 'N/A',
            perceivedAccuracy: '7.8/10',
            verificationRate: '12%',
          },
        },
        treatmentVersion: {
          description:
            'Same AI-generated summaries displayed with an "AI-Generated" badge, source links, and a "Verify against source" prompt',
          metrics: {
            conversionRate: 'N/A',
            perceivedAccuracy: '6.9/10',
            verificationRate: '41%',
          },
        },
        results: {
          winner: 'treatment',
          analysis:
            'Labeling AI content reduced blind trust (perceived accuracy dropped slightly, reflecting more calibrated assessment) but significantly increased verification behavior. Users who verified caught 23% more errors. Overall decision quality improved despite lower initial confidence.',
          learnings: [
            'Transparent AI labeling leads to more calibrated trust',
            'Verification prompts drive users to check sources, catching errors',
            'Unlabeled AI content creates false confidence that degrades decision quality',
            'Users preferred the labeled version in follow-up satisfaction surveys',
          ],
        },
      },
    ],
  },

  //===========================================
  // DETECTION
  //===========================================
  detection: {
    visualCues: [
      {
        name: 'Missing Author Labels',
        description:
          'Content blocks, posts, or messages displayed without visible author names or avatars',
        howToSpot:
          'Scan each content card or block: can you immediately identify who authored it?',
        severity: ImpactLevel.HIGH,
      },
      {
        name: 'Reshared Content Without Source Chain',
        description:
          'Forwarded or reshared content that only shows the latest sharer, not the original creator',
        howToSpot:
          'Look for shared/forwarded/reposted content and check whether the original author is visible',
        severity: ImpactLevel.HIGH,
      },
      {
        name: 'Unlabeled AI Content',
        description:
          'AI-generated text, summaries, or suggestions presented without any AI indicator',
        howToSpot:
          'Check whether AI-generated content has a distinct badge, icon, or visual treatment',
        severity: ImpactLevel.CRITICAL,
      },
      {
        name: 'Version History Without Authors',
        description:
          'Document or data change history showing only timestamps without identifying who made each change',
        howToSpot:
          'Open version history and check whether each entry shows an author name alongside the timestamp',
        severity: ImpactLevel.HIGH,
      },
      {
        name: 'Blended Quote Styles',
        description:
          'Quoted or cited text styled identically to the surrounding author\'s own words',
        howToSpot:
          'Look for inline quotes or citations and check if they have distinct visual treatment (indentation, borders, quotation marks)',
        severity: ImpactLevel.MEDIUM,
      },
    ],

    patterns: [
      {
        name: 'Source Stripping Pattern',
        description: 'Attribution is lost as content moves through sharing, forwarding, or embedding pipelines',
        indicators: [
          'Reshared posts without original author',
          'Embedded content without source link',
          'Copy-pasted text without attribution metadata',
          'Screenshots of content with author cropped out',
        ],
        severity: ImpactLevel.CRITICAL,
        confidence: 'high',
      },
      {
        name: 'AI Camouflage Pattern',
        description: 'AI-generated content styled identically to human-authored content with no distinguishing marks',
        indicators: [
          'AI summaries without badges',
          'AI suggestions inline with human text',
          'Chatbot responses styled as human messages',
          'Auto-generated reports without AI disclosure',
        ],
        severity: ImpactLevel.CRITICAL,
        confidence: 'high',
      },
      {
        name: 'Anonymous Collaboration Pattern',
        description: 'Collaborative edits or contributions presented without individual attribution',
        indicators: [
          'Shared documents without edit attribution',
          'Team dashboards without contributor names',
          'Aggregated changes without per-author breakdown',
          'Comments without visible author identity',
        ],
        severity: ImpactLevel.HIGH,
        confidence: 'high',
      },
      {
        name: 'Temporal Ambiguity Pattern',
        description: 'Content presented without clear timestamps, making it impossible to determine recency or sequence',
        indicators: [
          'Missing or vague timestamps ("a while ago")',
          'Content from different dates displayed at the same level',
          'No distinction between original publish date and reshare date',
          'Version numbers without dates',
        ],
        severity: ImpactLevel.MEDIUM,
        confidence: 'medium',
      },
    ],

    checklistQuestions: [
      'Can users identify the original author of every piece of content?',
      'Is reshared or forwarded content clearly distinguished from original content?',
      'Is AI-generated content visually distinct from human-authored content?',
      'Does version history show who made each change, not just when?',
      'Are quoted or cited passages visually distinct from the surrounding text?',
      'Does the sharing workflow preserve attribution through the full chain?',
      'Can users trace any claim or data point back to its original source?',
      'Are there clear timestamps on both original and reshared content?',
      'Do collaborative editing tools show per-author attribution?',
      'Is there a way for users to verify the source of any content block?',
    ],
  },

  //===========================================
  // AI INTENT
  //===========================================
  intent: {
    systemPrompt: `You are an expert in cognitive psychology and UX design, specializing in misattribution of memory.

Analyze the provided design for source attribution and provenance patterns. Identify:

1. **Source Attribution**: Whether content clearly identifies its author or origin
2. **Share Chain Integrity**: Whether reshared or forwarded content preserves original authorship
3. **AI Content Labeling**: Whether AI-generated content is clearly distinguished from human content
4. **Version Attribution**: Whether change history identifies who made each change
5. **Quote Distinction**: Whether cited or quoted content is visually distinct from original commentary

For each pattern found:
- Identify where source confusion could occur
- Assess the severity of potential misattribution
- Determine if users could confuse AI content with human content
- Evaluate whether version history supports accountability
- Suggest specific improvements for clearer attribution

Consider:
- Can users always identify who created content they are reading?
- Does the sharing pipeline preserve or strip attribution?
- Is AI-generated content labeled clearly and consistently?
- Can collaborative work be traced to individual contributors?
- Are there accessibility implications for attribution elements?

Provide actionable recommendations for preventing misattribution.`,

    outputSchema: {
      type: 'object',
      properties: {
        attributionPatterns: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              type: { type: 'string' },
              location: { type: 'string' },
              sourceClarity: { type: 'string' },
              misattributionRisk: { type: 'string' },
              aiContentLabeled: { type: 'boolean' },
              recommendation: { type: 'string' },
            },
            required: [
              'type',
              'location',
              'sourceClarity',
              'misattributionRisk',
            ],
          },
        },
        overallAssessment: {
          type: 'object',
          properties: {
            sourceAttributionScore: { type: 'number' },
            shareChainIntegrity: { type: 'number' },
            aiContentTransparency: { type: 'number' },
            versionTrackingScore: { type: 'number' },
          },
          required: [
            'sourceAttributionScore',
            'shareChainIntegrity',
            'aiContentTransparency',
            'versionTrackingScore',
          ],
        },
        recommendations: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              priority: { type: 'number' },
              title: { type: 'string' },
              description: { type: 'string' },
              expectedImpact: { type: 'string' },
            },
            required: ['priority', 'title', 'description'],
          },
        },
      },
      required: [
        'attributionPatterns',
        'overallAssessment',
        'recommendations',
      ],
    },
  },

  //===========================================
  // GUIDELINES
  //===========================================
  guidelines: {
    implementation: [
      {
        step: 1,
        title: 'Audit Content Sources',
        description:
          'Map every place in your interface where content is displayed and identify its possible sources (user-generated, AI, shared, editorial, third-party)',
        example:
          'Content audit reveals: 40% user-written, 25% reshared, 20% AI-generated, 15% editorial',
        tips: [
          'Include all content types: posts, comments, summaries, suggestions, notifications',
          'Track the full lifecycle: creation, editing, sharing, embedding',
          'Identify which sources are most likely to be confused with each other',
        ],
      },
      {
        step: 2,
        title: 'Design Attribution Labels',
        description:
          'Create a consistent visual system for identifying content origin: author badges, AI indicators, and source links',
        example:
          'Human content shows avatar + name; AI content shows AI badge + source; shared content shows "Shared from [author]"',
        tips: [
          'Use consistent placement (always top-left of content block)',
          'Make labels visible without hover or interaction',
          'Ensure labels are accessible to screen readers',
        ],
      },
      {
        step: 3,
        title: 'Preserve Attribution Through Sharing',
        description:
          'Ensure that when content is reshared, forwarded, or embedded, the original author remains visible',
        example:
          'Forwarded message shows: "Forwarded by Maria | Originally by David Kim, Mar 10"',
        tips: [
          'Store attribution as metadata that travels with the content',
          'Display the full chain: creator, editors, sharers',
          'Link back to the original source when possible',
        ],
      },
      {
        step: 4,
        title: 'Label AI-Generated Content',
        description:
          'Apply a distinct, consistent visual treatment to all AI-generated or AI-assisted content',
        example:
          'AI summaries show a purple "AI" badge, cite their source documents, and include a "Verify" link',
        tips: [
          'Use the same indicator across all AI content types (summaries, suggestions, drafts)',
          'State what sources the AI used',
          'Include a way for users to verify against original sources',
        ],
      },
      {
        step: 5,
        title: 'Build Version Attribution',
        description:
          'In collaborative tools, ensure every change is attributed to a specific author with timestamps',
        example:
          'Version history: "v3 by Sarah Chen, Mar 19 — Updated pricing section (diff available)"',
        tips: [
          'Show author, timestamp, and change summary for each version',
          'Allow diff comparison between any two versions',
          'Distinguish human edits from AI-generated changes',
        ],
      },
    ],

    dos: [
      'Show the original author on every content block, including reshared content',
      'Label AI-generated content with a distinct, consistent visual indicator',
      'Maintain full attribution chains through sharing and forwarding pipelines',
      'Include author identity in version history alongside timestamps',
      'Use distinct visual treatment for quoted or cited text',
      'Provide "View source" or provenance links for derived content',
      'Make attribution accessible to screen readers and keyboard users',
      'Allow users to verify the source of any content on demand',
    ],

    donts: [
      'Don\'t strip original author information when content is reshared',
      'Don\'t present AI-generated content as if a human wrote it',
      'Don\'t show version history with only timestamps and no author names',
      'Don\'t style quoted text identically to the quoting author\'s own words',
      'Don\'t rely solely on color to indicate content source',
      'Don\'t hide attribution behind hover states or secondary screens',
      'Don\'t mix editorial content with user-generated content without clear labels',
      'Don\'t allow AI suggestions to appear inline without any visual distinction',
    ],

    bestPractices: [
      {
        title: 'Persistent Inline Attribution',
        description:
          'Show author name and source directly on or adjacent to every content block, visible without interaction',
        rationale:
          'Users skim content quickly; if attribution requires a click or hover, it will be missed and misattribution will occur',
        example:
          'Every card in a feed includes: avatar, author name, timestamp, and source type badge',
      },
      {
        title: 'Chain-of-Attribution for Reshared Content',
        description:
          'When content is shared or forwarded, show both the original author and the sharer',
        rationale:
          'Without the chain, users attribute content to whichever name they see, which is usually the most recent sharer',
        example:
          '"Shared by Maria Lopez | Originally by David Kim, Mar 10" with link to original',
      },
      {
        title: 'Consistent AI Content Indicators',
        description:
          'Use a single, recognizable visual pattern for all AI-generated content across the entire product',
        rationale:
          'Inconsistent AI labeling trains users to miss it; a single pattern builds recognition',
        example:
          'Purple "AI" badge + light purple background tint + source citation + verify link',
      },
      {
        title: 'Diff-Based Version History',
        description:
          'Show not just who changed a document, but exactly what they changed, with visual diffs',
        rationale:
          'Knowing who edited is insufficient; users need to see what changed to correctly attribute specific content',
        example:
          'Click any version to see red (removed) and green (added) diffs, each attributed to the editor',
      },
      {
        title: 'Source Verification Affordances',
        description:
          'Provide easy ways for users to check the original source of any content',
        rationale:
          'Empowering users to verify reduces blind trust and misattribution',
        example:
          '"View original" link on reshared content; "View sources" on AI summaries',
      },
    ],

    accessibility: [
      {
        wcagLevel: 'AA',
        criterion: '1.3.1',
        guideline:
          'Info and Relationships - Attribution must be programmatically associated with content',
        implementation:
          'Use aria-labelledby or aria-describedby to associate author names and source badges with their content blocks so screen readers announce provenance',
      },
      {
        wcagLevel: 'AA',
        criterion: '1.4.1',
        guideline:
          'Use of Color - Don\'t rely solely on color to indicate content source',
        implementation:
          'Combine color-coded authorship with text labels, icons, or badges so color-blind users can identify content sources',
      },
      {
        wcagLevel: 'AA',
        criterion: '1.4.3',
        guideline:
          'Contrast - Attribution text must meet minimum contrast requirements',
        implementation:
          'Author names, timestamps, and source labels must have at least 4.5:1 contrast ratio, even when styled as secondary text',
      },
      {
        wcagLevel: 'AA',
        criterion: '4.1.2',
        guideline:
          'Name, Role, Value - AI content indicators must have accessible names',
        implementation:
          'AI badges must have aria-label="AI-generated content" so screen readers announce the content origin',
      },
    ],

    ethics: [
      {
        concern: 'AI Content Transparency',
        severity: 'critical',
        explanation:
          'Presenting AI-generated content without labeling it as such deceives users about authorship and may lead to false trust or misplaced credit',
        mitigation:
          'Always label AI-generated content with a visible badge and state the sources used. Never disguise AI output as human work.',
      },
      {
        concern: 'Attribution Stripping',
        severity: 'high',
        explanation:
          'Removing or failing to display original author information when content is reshared deprives creators of credit and misleads consumers',
        mitigation:
          'Preserve full attribution chains. The original author must remain visible through all shares, forwards, and embeds.',
      },
      {
        concern: 'False Attribution',
        severity: 'critical',
        explanation:
          'Attributing content to the wrong person, whether by design error or intentional misrepresentation, is a form of misinformation',
        mitigation:
          'Implement robust metadata tracking. Audit attribution accuracy regularly. Provide correction mechanisms.',
      },
      {
        concern: 'Ghostwriting Without Disclosure',
        severity: 'medium',
        explanation:
          'AI or other users drafting content that is published under someone else\'s name without disclosure creates false impressions of expertise',
        mitigation:
          'Indicate when content was co-authored, AI-assisted, or ghost-written. Use labels like "Drafted by AI, reviewed by [Name]".',
      },
    ],
  },

  //===========================================
  // RESOURCES
  //===========================================
  resources: {
    papers: [
      {
        title: 'The Seven Sins of Memory: How the Mind Forgets and Remembers',
        author: 'Schacter, D. L.',
        year: 1999,
        doi: '10.1037/0003-066X.54.3.182',
        description:
          'The foundational paper categorizing misattribution as one of seven fundamental memory failures, alongside transience, absent-mindedness, blocking, suggestibility, bias, and persistence',
        type: 'foundational',
      },
      {
        title: 'Source Monitoring and Memory Distortion',
        author: 'Johnson, M. K., Hashtroudi, S., & Lindsay, D. S.',
        year: 1993,
        doi: '10.1037/0033-2909.114.1.3',
        description:
          'Comprehensive framework for understanding how people monitor and misidentify the sources of their memories',
        type: 'foundational',
      },
      {
        title: 'Imagination Inflation: Imagining a Childhood Event Inflates Confidence That It Occurred',
        author: 'Garry, M., Manning, C. G., Loftus, E. F., & Sherman, S. J.',
        year: 1996,
        doi: '10.3758/BF03211743',
        description:
          'Demonstrates how vividly imagining an event increases confidence that it actually happened, a key mechanism of misattribution',
        type: 'advanced',
      },
      {
        title: 'Cryptomnesia: Delineating Inadvertent Plagiarism',
        author: 'Brown, A. S., & Murphy, D. R.',
        year: 1989,
        doi: '10.1037/0278-7393.15.3.432',
        description:
          'Explores how people inadvertently reproduce others\' ideas as their own due to source amnesia',
        type: 'advanced',
      },
    ],

    books: [
      {
        title: 'The Seven Sins of Memory: How the Mind Forgets and Remembers',
        author: 'Schacter, Daniel L.',
        year: 2001,
        isbn: '9780618219193',
        description:
          'The definitive book on memory failures including misattribution, by the psychologist who defined the framework',
        type: 'foundational',
      },
      {
        title: 'The Memory Illusion: Remembering, Forgetting, and the Science of False Memory',
        author: 'Shaw, Julia',
        year: 2016,
        isbn: '9780399576799',
        description:
          'Accessible exploration of false memories and source confusion, with implications for how we design information systems',
        type: 'practical',
      },
      {
        title: 'Eyewitness Testimony',
        author: 'Loftus, Elizabeth F.',
        year: 1996,
        isbn: '9780674287778',
        description:
          'Landmark work on how memory is reconstructive and prone to source confusion, with applications beyond legal testimony',
        type: 'foundational',
      },
    ],

    articles: [
      {
        title: 'Designing for Content Provenance in the Age of AI',
        author: 'Nielsen Norman Group',
        url: 'https://www.nngroup.com/articles/content-provenance/',
        description:
          'Practical UX guidelines for attributing content sources and labeling AI-generated content in user interfaces',
        type: 'practical',
      },
      {
        title: 'C2PA: Coalition for Content Provenance and Authenticity',
        author: 'C2PA',
        url: 'https://c2pa.org/',
        description:
          'Technical standard for embedding content provenance metadata, addressing misattribution at the infrastructure level',
        type: 'practical',
      },
    ],

    videos: [
      {
        title: 'The Seven Sins of Memory',
        author: 'Daniel Schacter (Harvard)',
        url: 'https://www.youtube.com/watch?v=0VhsRrRFmPg',
        description:
          'Lecture by Daniel Schacter explaining misattribution and other memory sins with research examples',
        type: 'foundational',
      },
    ],

    demos: [],
  },

  //===========================================
  // RELATIONSHIPS
  //===========================================
  relationships: {
    complements: [
      'source-monitoring', // Core mechanism behind misattribution
      'false-consensus-effect', // Misattributing one's views to others
      'confirmation-bias', // Misremembering sources that confirm beliefs
      'hindsight-bias', // Reconstructing memories to match outcomes
    ],

    conflicts: [
      'reality-monitoring', // Accurate source monitoring prevents misattribution
    ],

    confusedWith: [
      'suggestibility', // External suggestion creating false memories (related but distinct)
      'false-memory', // Broader category that includes misattribution
      'cryptomnesia', // A specific subtype of misattribution
    ],

    hierarchy: {
      parent: 'memory-bias',
      children: [
        'source-confusion',
        'cryptomnesia',
        'false-memory',
      ],
    },
  },
};
