/**
 * Template for Codex / generic agents (`AGENTS.md`). Pure function — embeds
 * the shared core body assembled by the context command.
 */
export function renderAgentsContext(core: string): string {
  return `# Cognivo Design System — Agent Context

Generated by \`cognivo context\`. Regenerate with \`cognivo context --agent codex\`
(hand edits below the marker header are discarded on regeneration).

${core}
`;
}
