/**
 * Template for Claude Code (`CLAUDE.md`). Pure function — embeds the shared
 * core body assembled by the context command.
 */
export function renderClaudeContext(core: string): string {
  return `# Cognivo Design System — Agent Context

Generated by \`cognivo context\`. Regenerate with \`cognivo context --agent claude\`
(hand edits below the marker header are discarded on regeneration).

${core}
`;
}
