/**
 * Template for Cursor (`.cursorrules`). Pure function — embeds the shared
 * core body assembled by the context command.
 */
export function renderCursorContext(core: string): string {
  return `# Cognivo Design System — Agent Context (Cursor rules)

Generated by \`cognivo context\`. Regenerate with \`cognivo context --agent cursor\`
(hand edits below the marker header are discarded on regeneration).

${core}
`;
}
