import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  build: {
    lib: {
      entry: {
        index: resolve(__dirname, 'src/index.ts'),
        registry: resolve(__dirname, 'src/utils/bias-registry.ts'),
        components: resolve(__dirname, 'src/components/index.ts'),
        'categories/perception': resolve(__dirname, 'src/categories/perception.ts'),
        'categories/decision-making': resolve(__dirname, 'src/categories/decision-making.ts'),
        'categories/memory': resolve(__dirname, 'src/categories/memory.ts'),
        'categories/social': resolve(__dirname, 'src/categories/social.ts'),
        'categories/attribution': resolve(__dirname, 'src/categories/attribution.ts'),
        'categories/emotional': resolve(__dirname, 'src/categories/emotional.ts'),
        'categories/cognitive': resolve(__dirname, 'src/categories/cognitive.ts'),
      },
      formats: ['es'],
    },
    rollupOptions: {
      external: ['lit', '@cognivo/core'],
      output: {
        manualChunks(id) {
          if (id.includes('/biases/') && !id.includes('/core/')) {
            // Extract the bias folder name from the path
            const match = id.match(/\/biases\/([^/]+)\//);
            if (match) {
              const biasFolder = match[1];
              // Map bias folders to their category chunks based on primary category
              const categoryMap: Record<string, string> = {
                // Perception
                'von-restorff-effect': 'biases-perception',

                // Decision Making
                'analysis-paralysis': 'biases-decision-making',
                'anticipated-regret': 'biases-decision-making',
                'buyers-remorse': 'biases-decision-making',
                'choice-overload': 'biases-decision-making',
                'commitment-bias': 'biases-decision-making',
                'consistency-bias-decision': 'biases-decision-making',
                'decision-fatigue': 'biases-decision-making',
                'decoy-effect': 'biases-decision-making',
                'default-bias': 'biases-decision-making',
                'default-effect': 'biases-decision-making',
                'duration-neglect-decision': 'biases-decision-making',
                'endowment-effect': 'biases-decision-making',
                'escalation-commitment': 'biases-decision-making',
                'hot-cold-empathy-gap': 'biases-decision-making',
                'hyperbolic-discounting': 'biases-decision-making',
                'ikea-effect': 'biases-decision-making',
                'inertia-bias': 'biases-decision-making',
                'intention-action-gap': 'biases-decision-making',
                'licensing-effect': 'biases-decision-making',
                'loss-aversion': 'biases-decision-making',
                'maximizing': 'biases-decision-making',
                'moral-licensing': 'biases-decision-making',
                'peltzman-effect': 'biases-decision-making',
                'planning-fallacy': 'biases-decision-making',
                'post-purchase-rationalization': 'biases-decision-making',
                'present-bias': 'biases-decision-making',
                'procrastination-bias': 'biases-decision-making',
                'proportion-dominance': 'biases-decision-making',
                'regret-aversion': 'biases-decision-making',
                'restraint-bias-decision': 'biases-decision-making',
                'risk-compensation': 'biases-decision-making',
                'satisficing': 'biases-decision-making',
                'scarcity-bias': 'biases-decision-making',
                'scope-insensitivity': 'biases-decision-making',
                'status-quo-bias': 'biases-decision-making',
                'sunk-cost-fallacy': 'biases-decision-making',
                'temporal-discounting': 'biases-decision-making',
                'time-inconsistency': 'biases-decision-making',
                'what-the-hell-effect': 'biases-decision-making',

                // Memory
                'attentional-bias': 'biases-memory',
                'changing-state-effect': 'biases-memory',
                'choice-supportive-bias': 'biases-memory',
                'consistency-bias': 'biases-memory',
                'context-dependent-memory': 'biases-memory',
                'cryptomnesia': 'biases-memory',
                'egocentric-bias': 'biases-memory',
                'fading-affect-bias': 'biases-memory',
                'false-memory': 'biases-memory',
                'generation-effect': 'biases-memory',
                'google-effect': 'biases-memory',
                'google-effect-digital': 'biases-memory',
                'hindsight-bias': 'biases-memory',
                'hindsight-bias-memory': 'biases-memory',
                'irrelevant-speech-effect': 'biases-memory',
                'levels-processing-effect': 'biases-memory',
                'misattribution-memory': 'biases-memory',
                'misinformation-effect': 'biases-memory',
                'modality-effect': 'biases-memory',
                'mood-congruent-memory': 'biases-memory',
                'next-in-line-effect': 'biases-memory',
                'peak-end-rule': 'biases-memory',
                'primacy-effect': 'biases-memory',
                'primacy-recency-effect': 'biases-memory',
                'recency-effect': 'biases-memory',
                'rosy-retrospection': 'biases-memory',
                'self-reference-effect': 'biases-memory',
                'serial-position-effect': 'biases-memory',
                'source-confusion': 'biases-memory',
                'spacing-effect': 'biases-memory',
                'state-dependent-memory': 'biases-memory',
                'suffix-effect': 'biases-memory',
                'suggestibility': 'biases-memory',
                'telescoping-effect': 'biases-memory',
                'testing-effect': 'biases-memory',
                'tip-of-tongue': 'biases-memory',
                'von-restorff-isolation': 'biases-memory',
                'word-length-effect': 'biases-memory',
                'zeigarnik-effect': 'biases-memory',

                // Social
                'authority-bias': 'biases-social',
                'bandwagon-effect': 'biases-social',
                'belief-in-just-world': 'biases-social',
                'bystander-effect': 'biases-social',
                'cautious-shift': 'biases-social',
                'cheerleader-effect': 'biases-social',
                'conformity-bias': 'biases-social',
                'cross-race-effect': 'biases-social',
                'diffusion-responsibility': 'biases-social',
                'empathy-gap-social': 'biases-social',
                'false-consensus-effect': 'biases-social',
                'false-uniqueness-effect': 'biases-social',
                'group-attribution-error': 'biases-social',
                'groupthink': 'biases-social',
                'horn-effect': 'biases-social',
                'identifiable-victim-effect': 'biases-social',
                'illusion-transparency': 'biases-social',
                'illusory-correlation-social': 'biases-social',
                'in-group-bias': 'biases-social',
                'ingroup-favoritism': 'biases-social',
                'just-world-hypothesis': 'biases-social',
                'linguistic-intergroup-bias': 'biases-social',
                'minimal-group-paradigm': 'biases-social',
                'obedience-bias': 'biases-social',
                'out-group-homogeneity': 'biases-social',
                'outgroup-homogeneity-effect': 'biases-social',
                'own-race-bias': 'biases-social',
                'physical-attractiveness-stereotype': 'biases-social',
                'pluralistic-ignorance': 'biases-social',
                'prejudice-bias': 'biases-social',
                'risky-shift': 'biases-social',
                'social-comparison-bias': 'biases-social',
                'social-proof': 'biases-social',
                'spotlight-effect': 'biases-social',
                'stereotyping': 'biases-social',
                'ultimate-attribution-error': 'biases-social',
                'victim-blaming': 'biases-social',

                // Cognitive (all remaining)
                'acquiescence-bias': 'biases-cognitive',
                'action-bias': 'biases-cognitive',
                'affect-heuristic': 'biases-cognitive',
                'agent-detection': 'biases-cognitive',
                'ambiguity-effect': 'biases-cognitive',
                'anchoring-adjustment': 'biases-cognitive',
                'anchoring-bias': 'biases-cognitive',
                'apophenia': 'biases-cognitive',
                'attribute-substitution': 'biases-cognitive',
                'availability-heuristic': 'biases-cognitive',
                'base-rate-fallacy': 'biases-cognitive',
                'clustering-illusion': 'biases-cognitive',
                'clustering-illusion-stats': 'biases-cognitive',
                'confirmation-bias': 'biases-cognitive',
                'conjunction-fallacy': 'biases-cognitive',
                'contrast-effect': 'biases-cognitive',
                'denomination-effect': 'biases-cognitive',
                'dunning-kruger-effect': 'biases-cognitive',
                'duration-neglect': 'biases-cognitive',
                'ellsberg-paradox': 'biases-cognitive',
                'empathy-gap': 'biases-cognitive',
                'fluency-heuristic': 'biases-cognitive',
                'focusing-illusion': 'biases-cognitive',
                'framing-bias': 'biases-cognitive',
                'framing-effect': 'biases-cognitive',
                'fundamental-attribution-error': 'biases-cognitive',
                'gamblers-fallacy': 'biases-cognitive',
                'halo-effect': 'biases-cognitive',
                'hot-hand-fallacy': 'biases-cognitive',
                'illusion-control': 'biases-cognitive',
                'illusory-correlation': 'biases-cognitive',
                'impact-bias': 'biases-cognitive',
                'law-small-numbers': 'biases-cognitive',
                'lucky-number-bias': 'biases-cognitive',
                'magical-thinking': 'biases-cognitive',
                'mental-accounting': 'biases-cognitive',
                'mere-exposure-effect': 'biases-cognitive',
                'money-illusion': 'biases-cognitive',
                'non-response-bias': 'biases-cognitive',
                'omission-bias': 'biases-cognitive',
                'optimism-bias': 'biases-cognitive',
                'outcome-bias': 'biases-cognitive',
                'overconfidence-bias': 'biases-cognitive',
                'pareidolia': 'biases-cognitive',
                'priming-effect': 'biases-cognitive',
                'projection-bias': 'biases-cognitive',
                'pseudocertainty-effect': 'biases-cognitive',
                'recognition-heuristic': 'biases-cognitive',
                'regression-toward-mean': 'biases-cognitive',
                'representativeness-heuristic': 'biases-cognitive',
                'response-bias': 'biases-cognitive',
                'restraint-bias': 'biases-cognitive',
                'sample-size-neglect': 'biases-cognitive',
                'sampling-bias': 'biases-cognitive',
                'selection-bias': 'biases-cognitive',
                'self-serving-bias': 'biases-cognitive',
                'simulation-heuristic': 'biases-cognitive',
                'social-desirability-bias': 'biases-cognitive',
                'superstition-bias': 'biases-cognitive',
                'survivorship-bias': 'biases-cognitive',
                'uncertainty-avoidance': 'biases-cognitive',
                'unit-bias': 'biases-cognitive',
                'volunteer-bias': 'biases-cognitive',
                'zero-risk-bias': 'biases-cognitive',
              };
              return categoryMap[biasFolder];
            }
          }
          return undefined;
        },
      },
    },
    sourcemap: true,
    minify: 'esbuild',
    target: 'es2022',
  },
});
