/**
 * HALO EFFECT
 */


import type { BiasCard } from '../core/types.js';
import {
  BiasCategory,
  ImpactLevel,
} from '../core/types.js';

export const haloEffect: BiasCard = {
  //===========================================
  // METADATA
  //===========================================
  metadata: {
    id: 'halo-effect',
    name: 'Halo Effect',
    aliases: ['Halo Error', 'Horn Effect (negative)'],
    category: BiasCategory.COGNITIVE,
    relatedCategories: [
      BiasCategory.DECISION_MAKING,
      BiasCategory.PERCEPTION,
      BiasCategory.MEMORY,
    ],
    tags: [
      'first-impression',
      'generalization',
      'attractiveness',
      'overall-impression',
    ],
  },

  //===========================================
  // DEFINITION
  //===========================================
  definition: {
    simple: 'A single positive trait makes us view all other traits more favorably.',

    detailed: `The Halo Effect is a cognitive bias where one prominent positive characteristic of a person, product, or brand influences our overall perception and judgment of all other characteristics. When we notice one good quality, we tend to assume other unrelated qualities are also positive, creating a "halo" of positivity around the entire entity.

This effect is particularly powerful in visual design and user experience. A beautiful interface can make users believe the product is more functional, faster, more secure, and more trustworthy - even before they've tested these qualities. Conversely, the Horn Effect (negative halo) occurs when one negative trait causes us to view everything else negatively.

The Halo Effect is one of the most influential biases in design because aesthetics and first impressions have outsized impact on user perception, trust, conversion rates, and long-term satisfaction. Companies like Apple have built entire brand strategies around leveraging this bias.`,

    psychologyBasis: {
      discoveredBy: 'Edward Thorndike',
      year: 1920,
      theory: 'Halo Effect',
      mechanism: `The brain forms a global evaluative impression from a single salient trait, then uses that impression as a filter for judging all other attributes. This happens because:

1. **Global Evaluation Transfer**: When we perceive one strong positive attribute (e.g., visual beauty), the brain generates a positive affective response that "spills over" to color judgments of unrelated qualities like reliability, intelligence, or trustworthiness
2. **Cognitive Consistency**: The brain seeks coherent mental models - once a positive impression forms, attributing negative qualities creates cognitive dissonance, so we unconsciously resolve it by assuming everything is positive
3. **Confirmation Bias Coupling**: After forming an initial positive impression, we selectively attend to evidence that confirms the overall positive evaluation and discount contradictory evidence
4. **Affect-as-Information**: The positive feeling generated by one trait (e.g., beautiful design) is misattributed as information about other traits (e.g., "this feels good, so it must be secure")
5. **Rapid Trait Inference**: The brain makes snap judgments within 50ms of seeing a design; these initial impressions then anchor all subsequent evaluations, making the halo remarkably resistant to correction`,
    },

    realWorldExample: `In Thorndike's original 1920 study, military officers rated soldiers on various traits like intelligence, leadership, and character. Officers who rated a soldier high on physical appearance also rated them high on completely unrelated traits like intelligence and leadership ability - even though physical appearance has no logical connection to these qualities. This demonstrated how one prominent positive trait creates a "halo" affecting all other judgments.`,
  },

  //===========================================
  // DESIGN IMPACT
  //===========================================
  designImpact: {
    description: `The Halo Effect profoundly shapes how users perceive digital products. A single strong positive impression - especially visual design quality - radiates outward to influence perceived usability, trustworthiness, performance, and value. Designers can leverage this to:

- Increase perceived reliability and security through polished visual design
- Build trust rapidly through high-quality first impressions during onboarding
- Transfer brand reputation to new features or products
- Elevate perceived product quality through consistent aesthetic excellence
- Shape overall satisfaction by investing in key "halo moments" in the user journey`,

    whenToUse: [
      {
        title: 'Onboarding First Impressions',
        scenario:
          'When introducing new users to your product for the first time',
        example:
          'Invest heavily in the visual polish and micro-interactions of your onboarding flow - users who have a beautiful first experience will assume the entire product is high quality',
        impact: ImpactLevel.CRITICAL,
      },
      {
        title: 'Landing Page and Marketing',
        scenario: 'When converting visitors into users or customers',
        example:
          'A visually stunning landing page with smooth animations and professional typography makes visitors assume the product itself is equally well-crafted',
        impact: ImpactLevel.CRITICAL,
      },
      {
        title: 'Trust and Security Perception',
        scenario: 'When users need to trust your product with sensitive data or payments',
        example:
          'A polished, professional checkout flow with refined design details makes users feel their financial information is more secure, even before seeing security badges',
        impact: ImpactLevel.HIGH,
      },
      {
        title: 'Brand Extension and New Features',
        scenario: 'When launching new products or features under an established brand',
        example:
          'Apple can launch a new product category and users immediately assume quality because the brand halo transfers from existing products',
        impact: ImpactLevel.HIGH,
      },
      {
        title: 'Error Recovery and Forgiveness',
        scenario: 'When users encounter bugs or issues in an otherwise polished product',
        example:
          'Users are more forgiving of occasional errors in a beautifully designed product because the halo effect maintains their overall positive impression',
        impact: ImpactLevel.MEDIUM,
      },
    ],

    whenToAvoid: [
      {
        title: 'Masking Usability Problems',
        reason:
          'Using visual polish to disguise fundamental usability issues',
        consequence:
          'Users initially attracted by aesthetics will churn when they discover the product does not actually work well',
        alternative:
          'Fix usability problems first, then enhance aesthetics. Visual design should complement, not replace, good UX',
      },
      {
        title: 'Safety-Critical Interfaces',
        reason:
          'Relying on aesthetic trust for medical, aviation, or financial systems where actual reliability matters more than perceived reliability',
        consequence:
          'Users may over-trust a beautiful interface and fail to verify critical information',
        alternative:
          'Prioritize clear information hierarchy, explicit confirmations, and functional reliability over visual flourish',
      },
      {
        title: 'Accessibility Trade-offs',
        reason:
          'Sacrificing accessibility for visual beauty (e.g., low contrast text, small fonts, animation-heavy interfaces)',
        consequence:
          'The halo effect only works for users who can perceive the visual quality; excluded users experience the opposite',
        alternative:
          'Design for beauty AND accessibility - they are not mutually exclusive. WCAG compliance can coexist with stunning design',
      },
      {
        title: 'Over-Promising Through Aesthetics',
        reason:
          'When the product cannot deliver on the quality expectations set by its visual design',
        consequence:
          'The gap between perceived quality (from design) and actual quality creates disappointment and negative word-of-mouth',
        alternative:
          'Ensure product quality matches the expectations your visual design creates. Invest in substance alongside style',
      },
    ],

    commonMistakes: [
      {
        title: 'All Style, No Substance',
        description:
          'Investing heavily in visual design while neglecting core functionality and performance',
        why: 'The halo effect creates initial positive impressions, but sustained usage reveals actual quality. The gap between expectation and reality causes a strong backlash (the "reverse halo")',
        fix: 'Balance investment between visual polish and functional quality. Use the halo effect to amplify genuinely good products, not to mask poor ones',
      },
      {
        title: 'Inconsistent Quality Signals',
        description:
          'Having beautiful marketing pages but rough in-app experiences, or polished primary flows but broken edge cases',
        why: 'Inconsistency breaks the halo - one sloppy screen can trigger the Horn Effect, reversing users\' positive impressions across the entire product',
        fix: 'Maintain consistent visual quality across ALL touchpoints. The weakest screen defines the user\'s revised impression',
      },
      {
        title: 'Ignoring the Horn Effect',
        description:
          'Not recognizing that one negative trait can undo the entire halo, causing users to judge everything negatively',
        why: 'Negative impressions are often stronger and more lasting than positive ones. A single ugly error page can taint the entire product perception',
        fix: 'Audit for "horn triggers" - error states, loading screens, empty states, and edge cases that might create negative impressions',
      },
      {
        title: 'Assuming Aesthetics Are Universal',
        description:
          'Using a single aesthetic approach for all user segments and cultures',
        why: 'What creates a positive halo varies by culture, age group, and context. Minimalist design signals quality to some but emptiness to others',
        fix: 'Research your specific audience. Test visual approaches with target users rather than relying on designer preferences',
      },
    ],

    impactAreas: {
      layout: {
        level: ImpactLevel.HIGH,
        description:
          'Layout cleanliness and spatial harmony contribute powerfully to the initial positive impression that drives the halo',
        examples: [
          'Generous whitespace signals sophistication and quality, creating a positive halo',
          'Balanced, symmetrical layouts feel more professional and trustworthy',
          'Cluttered layouts trigger the Horn Effect, making everything feel cheap',
          'Consistent spacing and alignment communicate attention to detail',
        ],
      },
      typography: {
        level: ImpactLevel.HIGH,
        description:
          'Typography quality is one of the strongest halo triggers - users unconsciously judge product quality by font choices',
        examples: [
          'Professional typeface selection signals brand maturity and reliability',
          'Consistent type hierarchy communicates organizational competence',
          'Poor font choices or inconsistent sizing trigger negative halo (Horn Effect)',
          'Elegant typography on key screens creates lasting positive impressions',
        ],
      },
      color: {
        level: ImpactLevel.CRITICAL,
        description:
          'Color is the most immediately perceived design attribute and a primary driver of initial emotional response and halo formation',
        examples: [
          'Sophisticated, harmonious color palettes signal professional quality',
          'Brand-consistent color usage reinforces the brand halo across touchpoints',
          'Jarring or clashing colors trigger the Horn Effect instantly',
          'Strategic use of accent colors on key interactions creates positive micro-halos',
        ],
      },
      interaction: {
        level: ImpactLevel.CRITICAL,
        description:
          'Smooth, responsive interactions are among the strongest halo generators because they feel "alive" and high-quality',
        examples: [
          'Fluid animations and transitions make users assume the entire product is well-engineered',
          'Responsive, instant feedback on user actions signals technical competence',
          'Laggy or janky interactions immediately trigger the Horn Effect',
          'Delightful micro-interactions create disproportionately positive impressions',
        ],
      },
      content: {
        level: ImpactLevel.HIGH,
        description:
          'Well-crafted content reinforces the halo effect by communicating competence and care',
        examples: [
          'Clear, well-written copy signals professionalism and builds trust',
          'Typos and grammatical errors trigger the Horn Effect, undermining perceived product quality',
          'Consistent voice and tone across the product reinforce brand halo',
          'Thoughtful empty states and error messages maintain the halo even in edge cases',
        ],
      },
      accessibility: {
        level: ImpactLevel.HIGH,
        description:
          'Accessibility determines whether the halo effect reaches all users or only those who can perceive visual design',
        examples: [
          'Screen reader users cannot perceive visual polish, so content quality and structure drive their halo',
          'Keyboard navigation smoothness creates its own interaction halo for keyboard users',
          'Accessible design signals care and quality, creating a halo for technically-literate evaluators',
          'Poor accessibility triggers a Horn Effect for users with disabilities and accessibility-conscious reviewers',
        ],
      },
    },
  },

  //===========================================
  // EXAMPLES
  //===========================================
  examples: {
    good: [
      {
        title: 'Polished Onboarding Creates Product Trust',
        description:
          'A fintech app with a beautifully animated onboarding flow that builds trust before users enter sensitive data',
        code: `<div class="onboarding-flow">
  <div class="step active" data-step="1">
    <div class="illustration-container">
      <!-- Smooth Lottie animation showing security -->
      <lottie-player src="secure-vault.json" autoplay loop></lottie-player>
    </div>
    <h2>Your money is safe with us</h2>
    <p class="subtitle">Bank-level 256-bit encryption protects every transaction</p>
    <div class="trust-signals">
      <span class="trust-badge">FDIC Insured</span>
      <span class="trust-badge">SOC 2 Certified</span>
    </div>
  </div>
  <div class="progress-dots">
    <span class="dot active"></span>
    <span class="dot"></span>
    <span class="dot"></span>
  </div>
  <button class="cta primary">Get Started</button>
</div>

<style>
.onboarding-flow {
  background: linear-gradient(135deg, var(--cg-color-surface), var(--cg-color-surface-elevated));
  border-radius: var(--cg-radius-xl);
  padding: var(--cg-space-8);
  text-align: center;
}
.illustration-container { margin-bottom: var(--cg-space-6); }
h2 { font-family: var(--cg-font-display); font-weight: 600; }
.subtitle { color: var(--cg-color-text-secondary); margin-top: var(--cg-space-2); }
.trust-badge {
  display: inline-flex;
  padding: var(--cg-space-1) var(--cg-space-3);
  background: var(--cg-color-success-subtle);
  color: var(--cg-color-success);
  border-radius: var(--cg-radius-full);
  font-size: var(--cg-text-sm);
  font-weight: 500;
}
</style>`,
        explanation:
          'The beautiful animation, clean typography, and polished visual design create an immediate positive impression. Users unconsciously transfer this "this is well-made" feeling to judgments about security, reliability, and trustworthiness - before seeing any actual security evidence.',
        principle:
          'Visual polish in first moments creates a trust halo that transfers to perceived security and reliability',
        metrics: {
          before: '23% completed account setup with basic onboarding',
          after: '41% completed account setup with polished onboarding',
          improvement: '78% increase in onboarding completion through design halo',
        },
      },
      {
        title: 'Consistent Design System Building Cumulative Halo',
        description:
          'An enterprise SaaS product using a meticulous design system where every component reflects the same quality standard',
        code: `<!-- Every component, from button to data table, shares
     the same visual language and quality level -->
<div class="dashboard">
  <header class="dashboard-header">
    <h1>Analytics Overview</h1>
    <div class="time-selector">
      <button class="segment active">7d</button>
      <button class="segment">30d</button>
      <button class="segment">90d</button>
    </div>
  </header>

  <div class="metric-grid">
    <div class="metric-card">
      <span class="metric-label">Revenue</span>
      <span class="metric-value">$142,847</span>
      <span class="metric-delta positive">+12.3%</span>
    </div>
    <div class="metric-card">
      <span class="metric-label">Users</span>
      <span class="metric-value">8,492</span>
      <span class="metric-delta positive">+5.7%</span>
    </div>
  </div>

  <!-- Even the empty state is beautiful -->
  <div class="empty-state">
    <svg class="empty-illustration"><!-- Elegant illustration --></svg>
    <h3>No alerts today</h3>
    <p>Everything is running smoothly. We'll notify you if anything needs attention.</p>
  </div>
</div>

<style>
.metric-card {
  background: var(--cg-color-surface);
  border-radius: var(--cg-radius-lg);
  padding: var(--cg-space-5);
  box-shadow: var(--cg-shadow-sm);
  transition: box-shadow 0.2s ease;
}
.metric-card:hover { box-shadow: var(--cg-shadow-md); }
.metric-delta.positive { color: var(--cg-color-success); }
.empty-state {
  text-align: center;
  padding: var(--cg-space-10);
  color: var(--cg-color-text-secondary);
}
</style>`,
        explanation:
          'When EVERY component - including empty states, loading states, and error messages - maintains the same high visual quality, users develop a deep, cumulative halo. They assume the engineering, data accuracy, and business logic are equally meticulous.',
        principle:
          'Consistent quality across all touchpoints builds a compound halo effect that increases with each interaction',
      },
      {
        title: 'Micro-Interactions Creating Perceived Performance',
        description:
          'Smooth transitions and animations that make the product feel faster and more responsive than it technically is',
        code: `<button class="action-button" onclick="handleSubmit()">
  <span class="button-text">Save Changes</span>
  <span class="button-loader">
    <svg class="spinner" viewBox="0 0 24 24">
      <circle cx="12" cy="12" r="10" stroke-dasharray="62" stroke-dashoffset="62">
        <animate attributeName="stroke-dashoffset" values="62;0" dur="1s" />
      </circle>
    </svg>
  </span>
  <span class="button-success">
    <svg class="checkmark"><path d="M5 12l5 5L19 7"/></svg>
  </span>
</button>

<style>
.action-button {
  position: relative;
  overflow: hidden;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  background: var(--cg-color-primary);
  color: var(--cg-color-on-primary);
  border-radius: var(--cg-radius-md);
  padding: var(--cg-space-3) var(--cg-space-6);
}
.action-button:active { transform: scale(0.98); }
.button-success .checkmark {
  stroke: var(--cg-color-on-primary);
  stroke-dasharray: 24;
  animation: draw-check 0.4s ease forwards;
}
@keyframes draw-check {
  to { stroke-dashoffset: 0; }
}
</style>`,
        explanation:
          'The smooth button press animation, loading spinner, and animated success checkmark make the interaction feel premium. Users perceive the entire application as faster and more reliable because each micro-interaction communicates craftsmanship.',
        principle:
          'Polished micro-interactions create a quality halo that extends to perceived performance and reliability',
        metrics: {
          before: 'Users rated app performance 6.2/10 with instant state changes',
          after: 'Users rated app performance 8.1/10 with animated transitions (same actual speed)',
          improvement: '31% increase in perceived performance through animation halo',
        },
      },
    ],

    bad: [
      {
        title: 'Beautiful But Broken',
        description:
          'A visually stunning app that prioritizes aesthetics over usability, relying entirely on the halo effect to retain users',
        code: `<!-- DON'T DO THIS -->
<div class="gorgeous-but-unusable">
  <!-- Beautiful hero but critical actions are buried -->
  <div class="hero" style="height: 80vh; background: linear-gradient(135deg, #667eea, #764ba2);">
    <h1 style="font-size: 4rem; color: white; opacity: 0.9;">Welcome</h1>
    <!-- Where's the CTA? Where's the navigation? -->
  </div>

  <!-- Gorgeous cards but no clear information hierarchy -->
  <div class="card" style="backdrop-filter: blur(20px); background: rgba(255,255,255,0.1);">
    <p style="color: rgba(255,255,255,0.6); font-size: 0.75rem;">
      Important account information hidden in low-contrast, tiny text
      because larger text would "ruin the aesthetic"
    </p>
  </div>

  <!-- Pretty icon-only navigation with no labels -->
  <nav>
    <button style="background: none; border: none;">
      <svg><!-- Mystery icon 1 --></svg>
    </button>
    <button style="background: none; border: none;">
      <svg><!-- Mystery icon 2 --></svg>
    </button>
  </nav>
</div>`,
        explanation:
          'This design is visually striking but sacrifices readability (low contrast text), discoverability (no labels on navigation), and usability (buried CTAs) for aesthetics. The initial halo will quickly reverse into a Horn Effect when users cannot accomplish their goals.',
        principle:
          'Never sacrifice usability for aesthetics - the halo effect amplifies good products but cannot save broken ones',
      },
      {
        title: 'Inconsistent Quality Creating Horn Effect',
        description:
          'A product with a polished marketing site but rough in-app experience',
        code: `<!-- DON'T DO THIS -->

<!-- Marketing site: Beautiful, polished -->
<div class="landing-page">
  <h1 style="font-family: 'Inter', sans-serif; font-weight: 700;">
    The Future of Project Management
  </h1>
  <p style="font-size: 1.25rem; color: #6b7280; line-height: 1.8;">
    Beautifully crafted for modern teams
  </p>
  <button style="background: #6366f1; color: white; padding: 16px 32px; border-radius: 12px;">
    Start Free Trial
  </button>
</div>

<!-- Actual app: Rough, inconsistent -->
<div class="actual-app">
  <h1 style="font-family: Arial; font-size: 14px; color: black;">
    Projects
  </h1>
  <table style="border: 1px solid #ccc; font-size: 12px;">
    <tr><td>Project 1</td><td>Active</td></tr>
  </table>
  <button style="background: #007bff; padding: 4px 8px;">
    New
  </button>
  <p style="color: red; font-size: 11px;">Error: Something went wrong</p>
</div>`,
        explanation:
          'The beautiful marketing site creates a strong positive halo, setting high expectations. When users encounter the rough, inconsistent in-app experience, the contrast triggers an amplified Horn Effect - they feel deceived, which is worse than if both experiences were mediocre.',
        principle:
          'Inconsistency between marketing and product quality creates a "bait and switch" that amplifies negative perception',
      },
      {
        title: 'Aesthetics Over Accessibility',
        description:
          'A design that creates a beautiful halo for sighted users while excluding those with disabilities',
        code: `<!-- DON'T DO THIS -->
<div class="exclusive-beauty">
  <!-- Light gray text on white: beautiful but fails WCAG -->
  <p style="color: #d1d5db; font-size: 0.875rem;">
    Important instructions that some users literally cannot read
  </p>

  <!-- Hover-only interactions: smooth but keyboard-inaccessible -->
  <div class="tooltip-trigger" style="cursor: pointer;">
    <span>Account Status</span>
    <!-- Tooltip only appears on mouse hover, no keyboard/focus support -->
    <div class="tooltip" style="display: none;">Your account expires in 3 days</div>
  </div>

  <!-- Autoplay video background: stunning but causes seizures -->
  <div style="position: fixed; z-index: -1;">
    <video autoplay loop muted>
      <source src="flashy-background.mp4">
    </video>
  </div>
</div>`,
        explanation:
          'This creates a halo effect ONLY for users without disabilities. For users with visual impairments, motor disabilities, or photosensitive conditions, it creates the opposite - a Horn Effect of exclusion. True design quality includes everyone.',
        principle:
          'A halo that only works for some users is not design quality - it is design discrimination',
      },
    ],

    realWorld: [
      {
        company: 'Apple',
        product: 'Hardware and Software Design',
        url: 'https://www.apple.com',
        description: 'Apple is the quintessential halo effect example. Their meticulous hardware design (unibody aluminum, precise tolerances, premium materials) creates a halo that extends to perceived software quality, customer service, and even perceived technical specifications. Users consistently rate Apple products as faster and more reliable than competitors with identical or superior specs.',
        effectiveness: 'very-effective',
        analysis: 'Apple has built the most valuable brand in the world largely through the halo effect. The premium physical design creates such a strong positive impression that it transfers to every aspect of the user experience. The "Apple tax" - the premium customers willingly pay - is essentially the monetized value of the halo effect.',
      },
      {
        company: 'Stripe',
        product: 'Developer Dashboard and API Documentation',
        url: 'https://stripe.com',
        description: 'Stripe\'s beautifully designed documentation and dashboard create a halo that makes developers perceive the API as more reliable, better-engineered, and easier to integrate. The visual quality of the docs communicates engineering excellence before developers write a single line of code.',
        effectiveness: 'very-effective',
        analysis: 'Stripe invests heavily in design for a developer-facing product, which is unusual in the payments space. The design halo transfers to perceived API reliability and engineering quality, helping Stripe win developers over competitors with comparable technical capabilities but rougher interfaces.',
      },
      {
        company: 'Airbnb',
        product: 'Listing Photography and App Design',
        url: 'https://www.airbnb.com',
        description: 'Airbnb invested in professional photography for listings, which created a halo effect where beautifully photographed properties were perceived as cleaner, safer, and better-located. The polished app design extends this halo to the overall Airbnb brand, making users trust the platform more than competitors.',
        effectiveness: 'very-effective',
        analysis: 'Professional photography was one of Airbnb\'s key growth insights. The visual quality halo increased bookings by 2-3x for photographed listings. Users transferred the quality of the photos to assumptions about property quality, host reliability, and neighborhood safety.',
      },
      {
        company: 'Tesla',
        product: 'Vehicle Interior and Software UI',
        url: 'https://www.tesla.com',
        description: 'Tesla\'s minimalist interior design and large touchscreen interface create a "tech company" halo that transfers to perceived vehicle quality, safety, and innovation. The software-first approach makes users perceive the car as more advanced than competitors with similar specifications.',
        effectiveness: 'effective',
        analysis: 'The design halo helps Tesla maintain premium pricing despite panel gaps and quality control issues that would damage traditional automakers more severely. However, this also demonstrates the limits of the halo effect - persistent quality issues eventually erode the halo for some users.',
      },
    ],

    abTests: [
      {
        title: 'Visual Polish Impact on Perceived Trustworthiness',
        hypothesis:
          'A more visually polished checkout flow will increase payment completion even with identical security features',
        controlVersion: {
          description:
            'Standard checkout form with basic styling: default form inputs, standard button, plain layout, same security badges',
          metrics: {
            conversionRate: '52%',
            timeOnPage: '2:45',
            scrollDepth: '100%',
          },
        },
        treatmentVersion: {
          description:
            'Polished checkout form with refined typography, smooth input animations, elegant card input component, subtle shadow depth, same security badges',
          metrics: {
            conversionRate: '64%',
            timeOnPage: '2:12',
            scrollDepth: '100%',
          },
        },
        results: {
          winner: 'treatment',
          analysis:
            'The visually polished checkout increased payment completion by 23%. Post-survey showed users rated the polished version as "more secure" (7.8 vs 5.9 out of 10) despite identical security features. Users spent LESS time on the polished version, indicating higher confidence.',
          learnings: [
            'Visual design quality directly impacts perceived security and trust',
            'Users completed the polished flow faster due to increased confidence',
            'The halo effect on security perception was strongest for first-time users',
            'The effect persisted even when users were told both versions had identical security',
          ],
        },
      },
      {
        title: 'Design System Consistency vs Inconsistency',
        hypothesis:
          'A consistent design system will create a stronger halo effect than an inconsistent but individually attractive interface',
        controlVersion: {
          description:
            'Product with mixed UI patterns: each screen designed independently with different styles, spacing, and component patterns (some screens are individually quite attractive)',
          metrics: {
            conversionRate: '38%',
            timeOnPage: '4:20',
            scrollDepth: '65%',
          },
        },
        treatmentVersion: {
          description:
            'Product with unified design system: every screen uses consistent components, spacing, typography, and color from a single design system',
          metrics: {
            conversionRate: '51%',
            timeOnPage: '3:05',
            scrollDepth: '82%',
          },
        },
        results: {
          winner: 'treatment',
          analysis:
            'The consistent design system increased sign-ups by 34%. Users rated the consistent version higher on "trustworthiness" (8.1 vs 6.4), "professionalism" (8.5 vs 6.8), and "would recommend to others" (7.9 vs 5.7). Consistency built a compound halo across the entire experience.',
          learnings: [
            'Design consistency matters more than individual screen beauty for halo effect',
            'Inconsistency triggers "something feels off" even if users cannot articulate why',
            'The compound halo from consistency increases with each additional consistent interaction',
            'Users exploring more of the product (higher scroll depth) suggests consistency builds confidence to explore',
          ],
        },
      },
    ],
  },

  //===========================================
  // DETECTION
  //===========================================
  detection: {
    visualCues: [
      {
        name: 'Disproportionate Visual Investment',
        description: 'Certain screens or flows receive significantly more design polish than others, suggesting intentional halo creation at key moments',
        howToSpot: 'Compare design quality across primary flows (onboarding, landing page, checkout) vs secondary flows (settings, error states, edge cases). Look for dramatic quality drops.',
        severity: ImpactLevel.HIGH,
      },
      {
        name: 'Premium Material Signals',
        description: 'Use of design elements that signal luxury, quality, or sophistication: subtle gradients, refined shadows, premium typography, generous whitespace',
        howToSpot: 'Look for glass-morphism effects, carefully crafted shadows, custom typefaces, or meticulous spacing that communicates "premium" before any content is read',
        severity: ImpactLevel.MEDIUM,
      },
      {
        name: 'Brand Consistency Anchoring',
        description: 'Strong visual brand elements (logo, colors, design language) from a trusted brand carried into new contexts to transfer the brand halo',
        howToSpot: 'Check if recognized brand elements are prominently placed to create association. Notice if a known brand\'s design language is applied to unfamiliar features.',
        severity: ImpactLevel.HIGH,
      },
      {
        name: 'Polished Micro-Interactions',
        description: 'Smooth animations, transitions, and interactive feedback that signal engineering quality and attention to detail',
        howToSpot: 'Interact with buttons, forms, and navigation. Look for custom animations, hover states, loading transitions, and success/error animations that go beyond defaults.',
        severity: ImpactLevel.MEDIUM,
      },
      {
        name: 'Photography and Imagery Quality',
        description: 'Professional, high-quality imagery that creates a positive aesthetic impression transferring to product perception',
        howToSpot: 'Assess whether photography is professional or stock, whether illustrations are custom or generic, whether imagery style is consistent and intentional.',
        severity: ImpactLevel.HIGH,
      },
    ],

    patterns: [
      {
        name: 'First Impression Investment Pattern',
        description: 'Heavy design investment in the first screens users see (landing page, onboarding, splash screen) to establish a positive halo that carries through the rest of the experience',
        indicators: ['Polished onboarding with custom animations', 'Landing page with higher design quality than inner pages', 'Carefully crafted splash screens or loading experiences', 'First-run tutorials with premium illustration and copy'],
        severity: ImpactLevel.CRITICAL,
        confidence: 'high',
      },
      {
        name: 'Brand Halo Transfer Pattern',
        description: 'Leveraging an established brand\'s positive reputation to create instant credibility for new products, features, or partnerships',
        indicators: ['Prominent brand logos on new product pages', '"By [trusted brand]" labeling', 'Consistent design language from parent brand', '"Powered by" or "Built on" associations'],
        severity: ImpactLevel.HIGH,
        confidence: 'high',
      },
      {
        name: 'Aesthetic-Usability Effect Pattern',
        description: 'Design that is beautiful enough to cause users to overlook or forgive usability issues (the aesthetic-usability effect is a direct manifestation of the halo effect)',
        indicators: ['High visual polish with questionable information architecture', 'Beautiful interfaces with hidden functionality', 'Style-forward design with unclear navigation', 'Users reporting product is "easy to use" despite measured usability problems'],
        severity: ImpactLevel.HIGH,
        confidence: 'medium',
      },
      {
        name: 'Quality Signal Clustering Pattern',
        description: 'Grouping multiple quality signals together (design polish + brand badges + social proof + professional imagery) to create a compound halo',
        indicators: ['Trust badges near polished UI elements', 'Professional testimonial photos alongside refined typography', 'Award logos near product screenshots', 'Multiple quality signals concentrated at decision points'],
        severity: ImpactLevel.MEDIUM,
        confidence: 'high',
      },
    ],

    checklistQuestions: [
      'What is the first visual impression users get, and what does it communicate about product quality?',
      'Is the design quality consistent across ALL screens, including error states, empty states, and settings?',
      'Are there screens where design quality drops noticeably compared to primary flows?',
      'Does the visual design create expectations that the product can actually deliver on?',
      'Is the design creating a positive halo for ALL users, including those with disabilities?',
      'Are micro-interactions and animations communicating quality or just adding decoration?',
      'Would a user who only sees the design (before using features) have an accurate impression of the product?',
      'Is the brand halo from marketing consistent with the in-product experience?',
      'Are there "horn triggers" - ugly or broken moments that could reverse the entire positive impression?',
      'Is visual polish being used to mask usability problems or to amplify genuine quality?',
    ],
  },

  //===========================================
  // AI INTENT
  //===========================================
  intent: {
    systemPrompt: `You are an expert in cognitive psychology and UX design, specializing in the halo effect and aesthetic-usability effect.

Analyze the provided design for halo effect patterns. Identify:

1. **Visual Quality Halo**: How visual polish influences perceived product quality, reliability, and trustworthiness
2. **Brand Halo Transfer**: How brand reputation or design language transfers positive perception to new features or products
3. **First Impression Impact**: How initial visual experiences set the tone for all subsequent interactions
4. **Consistency Assessment**: Whether design quality is consistent enough to maintain the halo across the entire experience
5. **Horn Effect Risks**: Where design quality drops might trigger negative perception reversal

For each pattern found:
- Identify the positive trait creating the halo and what unrelated qualities it influences
- Assess whether the halo is based on genuine quality or masking problems
- Determine if the halo works for all users (including those with disabilities)
- Evaluate the gap between perceived quality (from design) and actual quality (functionality)
- Suggest improvements for authentic, inclusive halo creation

Consider:
- Is the visual design creating accurate or misleading quality expectations?
- Are there inconsistencies that might break the halo (Horn Effect triggers)?
- Does the halo extend to accessibility, or does it exclude some users?
- Is the design leveraging the halo effect ethically - amplifying real quality rather than masking deficiencies?
- How durable is the halo? Will it survive sustained use?

Provide actionable recommendations for building an authentic, sustainable halo effect.`,

    outputSchema: {
      type: 'object',
      properties: {
        haloPatterns: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              type: { type: 'string' },
              location: { type: 'string' },
              positiveTrait: { type: 'string' },
              influencedPerceptions: { type: 'string' },
              authenticity: { type: 'string' },
              durability: { type: 'string' },
              ethical: { type: 'boolean' },
              recommendation: { type: 'string' },
            },
            required: [
              'type',
              'location',
              'positiveTrait',
              'influencedPerceptions',
              'ethical',
            ],
          },
        },
        overallAssessment: {
          type: 'object',
          properties: {
            visualQuality: { type: 'number' },
            consistencyScore: { type: 'number' },
            authenticityScore: { type: 'number' },
            accessibilityInclusion: { type: 'number' },
            ethicalScore: { type: 'number' },
          },
          required: [
            'visualQuality',
            'consistencyScore',
            'authenticityScore',
            'accessibilityInclusion',
            'ethicalScore',
          ],
        },
        recommendations: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              priority: { type: 'number' },
              title: { type: 'string' },
              description: { type: 'string' },
              expectedImpact: { type: 'string' },
            },
            required: ['priority', 'title', 'description'],
          },
        },
      },
      required: [
        'haloPatterns',
        'overallAssessment',
        'recommendations',
      ],
    },
  },

  //===========================================
  // GUIDELINES
  //===========================================
  guidelines: {
    implementation: [
      {
        step: 1,
        title: 'Identify Your Halo Moments',
        description:
          'Map the user journey and identify the key moments where first impressions are formed - these are your highest-leverage design investment points',
        example:
          'Landing page, onboarding flow, first successful action, checkout page - these moments disproportionately shape overall product perception',
        tips: [
          'Focus on the first 5 seconds of each critical screen',
          'Identify the single most important "wow moment" in your product',
          'Consider both visual and interaction quality at each touchpoint',
        ],
      },
      {
        step: 2,
        title: 'Establish Visual Quality Baseline',
        description:
          'Define and implement a design system that ensures consistent visual quality across every screen, including edge cases',
        example:
          'Create polished components for empty states, error messages, loading states, and settings pages - not just the marketing pages and primary flows',
        tips: [
          'The weakest screen defines your halo ceiling',
          'Audit EVERY screen for quality consistency',
          'Design error states and edge cases with the same care as hero screens',
        ],
      },
      {
        step: 3,
        title: 'Invest in Micro-Interaction Quality',
        description:
          'Add smooth animations, transitions, and interactive feedback that communicate engineering quality and attention to detail',
        example:
          'Button press animations, page transitions, loading state animations, success confirmations - each micro-interaction reinforces the quality halo',
        tips: [
          'Keep animations fast (200-300ms) to feel responsive, not slow',
          'Use easing curves that feel natural (ease-out for entries, ease-in for exits)',
          'Ensure animations respect prefers-reduced-motion for accessibility',
        ],
      },
      {
        step: 4,
        title: 'Ensure the Halo Is Earned',
        description:
          'Verify that your product\'s actual quality matches or exceeds the expectations created by your visual design',
        example:
          'If your checkout looks premium, your support experience, error handling, and data reliability must also be premium',
        tips: [
          'Survey users on perceived quality vs experienced quality',
          'Track satisfaction over time - a false halo creates initial high scores that drop',
          'Invest in engineering quality proportional to design quality',
        ],
      },
      {
        step: 5,
        title: 'Audit for Horn Effect Triggers',
        description:
          'Systematically find and fix moments where design quality drops and could reverse the positive halo',
        example:
          'Check error pages, 404s, form validation messages, loading failures, empty states - any moment of friction or visual roughness',
        tips: [
          'Use the product in airplane mode, with slow connections, and with incorrect inputs',
          'Check all emails, notifications, and transactional communications for quality consistency',
          'Review third-party integrations that might break your visual consistency',
        ],
      },
    ],

    dos: [
      'Invest heavily in the first 5 seconds of user experience - first impressions create the strongest halo',
      'Maintain consistent design quality across ALL screens, including error states and edge cases',
      'Use polished micro-interactions to communicate engineering quality',
      'Build the halo on genuine product quality - use design to amplify real strengths',
      'Design beautiful empty states, loading states, and error states - these are halo-critical moments',
      'Ensure visual quality extends to emails, notifications, and all communication touchpoints',
      'Test with real users to verify the halo creates accurate (not inflated) quality perceptions',
      'Include accessibility in your quality baseline - an exclusive halo is not true quality',
    ],

    donts: [
      'Don\'t use visual polish to mask fundamental usability or reliability problems',
      'Don\'t create a marketing-to-product quality gap that triggers a reverse halo (Horn Effect)',
      'Don\'t sacrifice readability, contrast, or accessibility for aesthetic beauty',
      'Don\'t assume one beautiful screen will compensate for many rough ones',
      'Don\'t ignore edge cases, error states, and secondary flows in your design investment',
      'Don\'t rely on the halo effect as a substitute for actual product quality',
      'Don\'t use design polish to create false trust for products handling sensitive data',
      'Don\'t assume your aesthetic preferences match your users\' - test with target audiences',
    ],

    bestPractices: [
      {
        title: 'Design Systems as Halo Infrastructure',
        description:
          'Build a comprehensive design system that ensures every component, screen, and state maintains the same quality level',
        rationale:
          'Consistent quality compounds the halo effect with each interaction. A design system is the infrastructure that makes this sustainable.',
        example:
          'Stripe\'s design system ensures their dashboard, docs, and checkout all feel like the same premium product',
      },
      {
        title: 'Edge Cases Are Halo-Critical',
        description:
          'Invest as much design effort in error states, empty states, loading, and settings as in marketing and primary flows',
        rationale:
          'One ugly error page can trigger the Horn Effect, undoing the halo built by 20 beautiful screens',
        example:
          'GitHub\'s custom 404 page and error pages maintain the brand halo even when things go wrong',
      },
      {
        title: 'Authentic Halo Over Performative Polish',
        description:
          'Ensure visual quality reflects actual product quality rather than creating unrealistic expectations',
        rationale:
          'A sustainable halo is built on genuine quality. Users who discover the halo was misleading become the harshest critics.',
        example:
          'Invest $1 in engineering quality for every $1 in visual design quality to keep perceived and actual quality aligned',
      },
      {
        title: 'Inclusive Quality Signals',
        description:
          'Ensure the halo effect works for ALL users, not just those who can perceive visual design',
        rationale:
          'Screen reader users, keyboard users, and users with visual impairments deserve the same quality experience and trust signals',
        example:
          'Smooth keyboard navigation, well-structured headings, and thoughtful screen reader announcements create a non-visual halo',
      },
      {
        title: 'Monitor Halo Durability',
        description:
          'Track whether the initial positive impression is sustained or erodes over time as users discover the real product',
        rationale:
          'If satisfaction scores drop significantly from week 1 to month 3, the halo was not earned',
        example:
          'Compare NPS scores at 1 day, 1 week, 1 month, and 3 months. Stable or increasing scores indicate an authentic halo.',
      },
    ],

    accessibility: [{
        wcagLevel: 'AA',
        criterion: '1.4.3',
        guideline:
          'Contrast (Minimum) - Never sacrifice text contrast for aesthetic beauty',
        implementation:
          'Ensure all text meets 4.5:1 contrast ratio minimum, even when using subtle, sophisticated color palettes. Beauty and readability are not mutually exclusive.',
      },
      {
        wcagLevel: 'AA',
        criterion: '2.3.1',
        guideline:
          'Three Flashes or Below Threshold - Ensure polished animations do not trigger seizures',
        implementation:
          'All animations and micro-interactions must avoid flashing more than 3 times per second. Respect prefers-reduced-motion media query.',
      },
      {
        wcagLevel: 'AA',
        criterion: '1.3.1',
        guideline:
          'Info and Relationships - Quality signals must be available to assistive technology',
        implementation:
          'Ensure trust badges, quality indicators, and brand signals have proper semantic HTML and ARIA labels so screen reader users receive equivalent trust signals.',
      },
      {
        wcagLevel: 'AA',
        criterion: '2.1.1',
        guideline:
          'Keyboard - Interactive design flourishes must be keyboard accessible',
        implementation:
          'All micro-interactions, hover effects, and animated elements that communicate quality must have keyboard-accessible equivalents.',
      },
    ],

    ethics: [
      {
        concern: 'False Trust Through Design',
        severity: 'critical',
        explanation:
          'Using polished visual design to create unearned trust in products handling sensitive data (financial, medical, personal) when the underlying security or reliability does not match the perceived quality',
        mitigation:
          'Ensure actual security, data handling, and reliability match the quality communicated by design. Conduct security audits proportional to the trust your design creates.',
      },
      {
        concern: 'Masking Deficiencies',
        severity: 'high',
        explanation:
          'Using aesthetic polish to distract from known usability problems, bugs, or missing features',
        mitigation:
          'Fix underlying issues rather than papering over them with design polish. Use the halo effect to amplify genuine quality, never to disguise deficiencies.',
      },
      {
        concern: 'Exclusive Quality Signaling',
        severity: 'high',
        explanation:
          'Creating a halo effect that only works for able-bodied, sighted users while excluding users with disabilities from the trust and quality signals',
        mitigation:
          'Design for inclusive quality. Ensure accessibility is part of the quality baseline, not an afterthought. Non-visual users deserve equivalent quality signals.',
      },
      {
        concern: 'Expectation-Reality Gap',
        severity: 'medium',
        explanation:
          'Creating such strong positive expectations through design that users are inevitably disappointed by the actual product experience',
        mitigation:
          'Calibrate design quality to product quality. Monitor satisfaction trajectory over time. If it drops after initial use, the halo may be creating false expectations.',
      },
    ],
  },

  //===========================================
  // RESOURCES
  //===========================================
  resources: {
    papers: [
      {
        title: 'A Constant Error in Psychological Ratings',
        author: 'Thorndike, E. L.',
        year: 1920,
        doi: '10.1037/h0071663',
        description:
          'The foundational paper introducing the Halo Effect, demonstrating how officers\' ratings of soldiers showed strong correlations between unrelated traits',
        type: 'foundational',
      },
      {
        title: 'The Halo Effect and Other Managerial Delusions',
        author: 'Rosenzweig, P.',
        year: 2007,
        description:
          'Analysis of how the halo effect distorts business judgments and organizational research',
        type: 'practical',
      },
      {
        title: 'The Halo Effect: Evidence for Unconscious Alteration of Judgments',
        author: 'Nisbett, R. E., & Wilson, T. D.',
        year: 1977,
        doi: '10.1037/0022-3514.35.4.250',
        description:
          'Landmark study demonstrating that the halo effect operates unconsciously - people are unaware their overall impression influences specific trait judgments',
        type: 'foundational',
      },
      {
        title: 'Attention Web Designers: You Have 50 Milliseconds to Make a Good First Impression!',
        author: 'Lindgaard, G., Fernandes, G., Dudek, C., & Brown, J.',
        year: 2006,
        doi: '10.1080/01449290500330448',
        description:
          'Research showing that users form aesthetic judgments of websites within 50ms, establishing the basis for visual design halos in digital products',
        type: 'advanced',
      },
      {
        title: 'What is Beautiful is Usable',
        author: 'Tractinsky, N., Katz, A. S., & Ikar, D.',
        year: 2000,
        doi: '10.1016/S0953-5438(00)00031-X',
        description:
          'Key study demonstrating the aesthetic-usability effect: attractive interfaces are perceived as more usable, a direct manifestation of the halo effect in HCI',
        type: 'foundational',
      },
    ],

    books: [
      {
        title: 'Emotional Design: Why We Love (or Hate) Everyday Things',
        author: 'Norman, Don',
        year: 2004,
        isbn: '9780465051366',
        description:
          'Norman explains how emotional responses to design (including the halo effect) influence usability perception across visceral, behavioral, and reflective levels',
        type: 'foundational',
      },
      {
        title: 'The Halo Effect... and Eight Other Business Delusions',
        author: 'Rosenzweig, Phil',
        year: 2007,
        isbn: '9780743291255',
        description:
          'Comprehensive analysis of how the halo effect distorts business thinking, including brand perception and product evaluation',
        type: 'practical',
      },
      {
        title: 'Thinking, Fast and Slow',
        author: 'Kahneman, Daniel',
        year: 2011,
        isbn: '9780374275631',
        description:
          'Kahneman\'s discussion of the halo effect as a manifestation of System 1 thinking, where initial impressions color all subsequent judgments',
        type: 'foundational',
      },
    ],

    articles: [
      {
        title: 'The Aesthetic-Usability Effect',
        author: 'Nielsen Norman Group',
        url: 'https://www.nngroup.com/articles/aesthetic-usability-effect/',
        description:
          'Practical guide to how the halo effect manifests as the aesthetic-usability effect in digital interfaces, with design recommendations',
        type: 'practical',
      },
      {
        title: 'First Impressions Matter: How Designers Can Support Humans\' Automatic Cognitive Processing',
        author: 'Nielsen Norman Group',
        url: 'https://www.nngroup.com/articles/first-impressions-human-automaticity/',
        description:
          'Research-backed analysis of how first impressions create halos in digital product experiences',
        type: 'practical',
      },
    ],

    videos: [
      {
        title: 'The Halo Effect - Science of Attraction',
        author: 'Veritasium',
        url: 'https://www.youtube.com/watch?v=eFwKhmBxpVo',
        description:
          'Clear explanation of the Halo Effect with compelling visual demonstrations of how one trait influences overall perception',
        type: 'foundational',
      },
    ],

    demos: [],
  },

  //===========================================
  // RELATIONSHIPS
  //===========================================
  relationships: {
    complements: [
      'social-proof',
      'recency-effect',
      'von-restorff-effect',
      'loss-aversion',
    ],

    conflicts: [
      'base-rate-neglect',
    ],

    confusedWith: [
      'recency-bias',
      'salience-bias',
      'vividness-effect',
    ],

    hierarchy: {
      parent: 'cognitive-bias',
      children: [
        'recency-bias',
        'salience-bias',
      ],
    },
  },
};
