/**
 * SCOPE INSENSITIVITY
 *
 * Our valuation doesn't scale with scope or magnitude
 */


import type { BiasCard } from '../core/types.js';
import {
  BiasCategory,
  ImpactLevel,
} from '../core/types.js';

export const scopeInsensitivity: BiasCard = {
  //===========================================
  // METADATA
  //===========================================
  metadata: {
    id: 'scope-insensitivity',
    name: 'Scope Insensitivity',
    aliases: ['Scope Neglect', 'Scope Insensitivity Bias', 'Valuation by Prototype'],
    category: BiasCategory.DECISION_MAKING,
    relatedCategories: [
      BiasCategory.DECISION_MAKING,
      BiasCategory.PERCEPTION,
      BiasCategory.COGNITIVE,
    ],
    tags: [
      'decision-making',
      'judgment',
      'scale',
      'magnitude',
      'numbers',
      'valuation',
      'data-visualization',
      'impact-communication',
    ],
  },

  //===========================================
  // DEFINITION
  //===========================================
  definition: {
    simple: 'Our valuation doesn\'t scale with scope or magnitude',

    detailed: `Scope insensitivity (also called scope neglect) is a cognitive bias where people's emotional and evaluative responses fail to scale proportionally with the magnitude of a problem or quantity. When asked how much they would pay to save 2,000 migrating birds from drowning in oil ponds, people offered roughly the same amount as when asked to save 20,000 or 200,000 birds.

This occurs because the brain evaluates scope through a mental prototype—a single vivid image of a bird struggling in oil—rather than through arithmetic multiplication. The feeling generated by that prototype doesn't change much whether the number is 2,000 or 200,000. The emotional response saturates quickly.

In UX and product design, scope insensitivity manifests when users fail to distinguish between large and small quantities, impacts, or magnitudes. Dashboards showing millions of data points, charity campaigns presenting abstract statistics, and metric displays with raw numbers all suffer when designers don't account for the human inability to intuitively grasp scale.`,

    psychologyBasis: {
      discoveredBy: 'Daniel Kahneman and various researchers',
      year: 1986,
      theory: 'Valuation by Prototype / Affect Heuristic',
      mechanism: `The brain forms a mental prototype of the situation and evaluates that prototype rather than the full scope. This happens because:

1. **Prototype Evaluation**: The mind generates a single representative image (one oil-covered bird) and values that image, regardless of the total number affected
2. **Affect Saturation**: Emotional response reaches a ceiling quickly—feeling "bad" about 2,000 deaths doesn't feel 100x worse than feeling bad about 20 deaths
3. **Logarithmic Perception**: Human perception of quantity follows a roughly logarithmic curve—the difference between 10 and 100 feels larger than between 100,000 and 1,000,000
4. **Failure of Multiplication**: People cannot intuitively multiply feelings by large numbers; "saving one life" times 200,000 doesn't yield 200,000x the emotional weight
5. **Narrative Collapse**: A single identifiable victim generates more empathy than statistical millions (the "identifiable victim effect")

The mechanism is deeply rooted in how the brain processes quantity—we evolved to handle small numbers and local groups, not millions or billions.`,
    },

    realWorldExample: `In a landmark 1992 study by Desvousges et al., participants were asked how much they would pay to prevent migratory birds from drowning in uncovered oil ponds. One group was told 2,000 birds were at risk, another 20,000, and a third 200,000. The average willingness to pay was $80, $78, and $88 respectively—virtually identical despite a 100x difference in scope.

This same insensitivity explains why a single child trapped in a well generates millions in donations and round-the-clock news coverage, while a famine affecting millions barely registers emotionally. Joseph Stalin reportedly observed that "one death is a tragedy; a million deaths is a statistic"—an intuitive grasp of scope insensitivity.`,
  },

  //===========================================
  // DESIGN IMPACT
  //===========================================
  designImpact: {
    description: `Scope insensitivity profoundly affects how users interpret data, perceive impact, and make decisions involving quantities in interfaces. Designers must actively counteract this bias to help users grasp the true scale of information. Key areas include:

- Data visualization design that makes scale differences perceptible and meaningful
- Impact communication that bridges the gap between abstract numbers and felt understanding
- Charity and donation interfaces that convey the real magnitude of need and contribution
- Metric dashboards that help users distinguish between small and large changes
- Environmental, health, and financial reporting that makes statistics tangible`,

    whenToUse: [
      {
        title: 'Data Visualization Scale',
        scenario:
          'When displaying quantities that vary by orders of magnitude',
        example:
          'Use proportional area charts, human-scale analogies, and progressive zoom to help users perceive the difference between 1,000 and 1,000,000',
        impact: ImpactLevel.CRITICAL,
      },
      {
        title: 'Impact Communication',
        scenario: 'When communicating the magnitude of a problem, achievement, or change',
        example:
          'Instead of "We reduced CO2 by 500,000 tons," show "That\'s equivalent to taking 108,000 cars off the road for a year"',
        impact: ImpactLevel.HIGH,
      },
      {
        title: 'Charity and Donation Amounts',
        scenario: 'When encouraging donations and communicating charitable impact',
        example:
          'Show concrete per-unit impact: "$25 provides clean water for one family for a month" with a visual of that family, then let users multiply',
        impact: ImpactLevel.HIGH,
      },
      {
        title: 'Metric Dashboards',
        scenario: 'When displaying KPIs, analytics, or performance metrics',
        example:
          'Use relative comparisons, sparklines with context, and human-scale reference points instead of raw large numbers',
        impact: ImpactLevel.HIGH,
      },
      {
        title: 'Risk Communication',
        scenario: 'When helping users understand the magnitude of risks or probabilities',
        example:
          'Use icon arrays (1,000 person icons with 3 highlighted) instead of saying "0.3% risk" to make probability viscerally real',
        impact: ImpactLevel.MEDIUM,
      },
      {
        title: 'Progress and Achievement Displays',
        scenario: 'When showing cumulative progress or milestones',
        example:
          'Break large goals into human-scale chunks: "You\'ve helped 47 students this month" rather than "Contributing to the education of 12,000 students annually"',
        impact: ImpactLevel.MEDIUM,
      },
    ],

    whenToAvoid: [
      {
        title: 'Deliberate Minimization',
        reason:
          'Using scope insensitivity to make large negative impacts seem small',
        consequence:
          'Users underestimate real harm or risk, leading to poor decisions and eroded trust',
        alternative:
          'Use concrete analogies and visual scaling to make negative impacts appropriately felt',
      },
      {
        title: 'Inflating Small Impacts',
        reason:
          'Using scaling techniques to make trivially small quantities seem large',
        consequence:
          'Users overreact to insignificant changes or differences',
        alternative:
          'Present small quantities honestly with appropriate context and benchmarks',
      },
      {
        title: 'Emotional Manipulation for Fundraising',
        reason:
          'Exploiting identifiable victim effect to drive donations while obscuring how funds are actually used',
        consequence:
          'Misallocation of resources, donor fatigue, and loss of trust',
        alternative:
          'Combine individual stories with transparent aggregate impact data and allocation breakdowns',
      },
      {
        title: 'Oversimplification of Complex Data',
        reason:
          'Reducing multidimensional data to a single human-scale analogy that loses critical nuance',
        consequence:
          'Users make decisions based on oversimplified mental models',
        alternative:
          'Provide layered information: analogy first, then detailed data for those who want depth',
      },
    ],

    commonMistakes: [
      {
        title: 'Displaying Raw Large Numbers Without Context',
        description:
          'Showing metrics like "2,847,391 API calls" or "$14.2M revenue" without reference points',
        why: 'Humans cannot intuitively grasp the difference between millions and billions; raw numbers become meaningless labels',
        fix: 'Add human-scale comparisons, trend indicators, and benchmarks: "2.8M calls—3x more than last quarter"',
      },
      {
        title: 'Using Identical Visual Weight for Different Magnitudes',
        description:
          'Displaying "12 errors" and "12,000 errors" in the same-sized badge or card',
        why: 'Without visual scaling, users perceive these as roughly equivalent because the badge design triggers the same emotional response',
        fix: 'Scale visual indicators proportionally—use color intensity, size, animation, or progressive disclosure to convey magnitude',
      },
      {
        title: 'Relying on Abstract Statistics for Impact',
        description:
          'Charity pages saying "We helped 500,000 people" without making that number tangible',
        why: 'The prototype image of "a person being helped" generates the same feeling whether the number is 500 or 500,000',
        fix: 'Use concrete breakdowns: "That\'s every person in the city of Tucson" or visual representations like filled stadiums',
      },
      {
        title: 'Linear Scales for Exponential Data',
        description:
          'Plotting data that varies by orders of magnitude on a linear axis',
        why: 'Small values become invisible while large values dominate, preventing users from perceiving the full range',
        fix: 'Use logarithmic scales with clear labels, or break data into meaningful ranges with separate visualizations',
      },
    ],

    impactAreas: {
      layout: {
        level: ImpactLevel.HIGH,
        description:
          'Layout determines how quantities are spatially represented and compared',
        examples: [
          'Proportional area displays make magnitude differences visible at a glance',
          'Side-by-side comparisons with scaled elements help users perceive 10x vs 100x differences',
          'Progressive disclosure reveals layers of magnitude (overview, then detail)',
          'Grid layouts with proportionally sized cards convey relative importance',
        ],
      },
      typography: {
        level: ImpactLevel.MEDIUM,
        description:
          'Typography can reinforce or undermine magnitude perception through size and emphasis',
        examples: [
          'Scaling font size proportionally with magnitude (within readable bounds) signals importance',
          'Using unit labels ("thousands", "millions") prevents number blindness',
          'Bold emphasis on magnitude-changing digits draws attention to scale shifts',
          'Consistent number formatting (1K, 1M, 1B) helps users parse magnitude quickly',
        ],
      },
      color: {
        level: ImpactLevel.HIGH,
        description:
          'Color intensity and heatmaps are powerful tools for conveying magnitude',
        examples: [
          'Graduated color scales (light to dark) map to quantity ranges, making magnitude visible',
          'Heatmaps use color intensity to convey density and concentration across geographic or temporal data',
          'Threshold-based color coding (green/yellow/red) creates meaningful magnitude breakpoints',
          'Opacity gradients can represent confidence or magnitude in overlapping data',
        ],
      },
      interaction: {
        level: ImpactLevel.CRITICAL,
        description:
          'Interactive exploration helps users build intuition for scale through direct manipulation',
        examples: [
          'Zoom controls let users explore data at different magnitude levels',
          'Hover tooltips that show concrete comparisons ("equal to X football fields") build scale intuition',
          'Slider controls that snap to human-scale benchmarks (1 person, 1 family, 1 city, 1 country)',
          'Animated transitions between magnitude levels help users perceive the jump from thousands to millions',
        ],
      },
      content: {
        level: ImpactLevel.CRITICAL,
        description:
          'Content framing determines whether users grasp or ignore the true scale of information',
        examples: [
          'Human-scale analogies ("enough water to fill 50 Olympic swimming pools") make abstract quantities tangible',
          'Per-unit breakdowns ("$0.03 per user") make large totals comprehensible',
          'Comparative framing ("more people than the entire population of Iceland") provides intuitive scale',
          'Narrative context explaining what a number means in practice prevents scope-blind reading',
        ],
      },
      accessibility: {
        level: ImpactLevel.HIGH,
        description:
          'Magnitude communication must work across all sensory modalities',
        examples: [
          'Screen readers need verbal magnitude cues since visual scaling is invisible ("significantly higher at 50,000 compared to baseline of 500")',
          'Alt text on charts must describe relative magnitude, not just data points',
          'Sonification (using pitch or volume) can convey magnitude for visually impaired users',
          'ARIA labels should include contextual magnitude information for data visualizations',
        ],
      },
    },
  },

  //===========================================
  // EXAMPLES
  //===========================================
  examples: {
    good: [
      {
        title: 'Concrete Comparison for Environmental Impact',
        description:
          'Climate dashboard translating CO2 reductions into tangible human-scale equivalents',
        code: `<div class="impact-display">
  <h3>Your Company's Carbon Reduction This Year</h3>
  <div class="metric-primary">
    <span class="number">47,500</span>
    <span class="unit">metric tons of CO2 avoided</span>
  </div>
  <div class="scale-comparisons">
    <div class="comparison">
      <span class="icon" aria-hidden="true">&#x1F697;</span>
      <p>Equal to taking <strong>10,326 cars</strong> off the road for a year</p>
    </div>
    <div class="comparison">
      <span class="icon" aria-hidden="true">&#x1F333;</span>
      <p>Or planting <strong>785,000 trees</strong> and letting them grow for 10 years</p>
    </div>
    <div class="comparison">
      <span class="icon" aria-hidden="true">&#x1F3D8;</span>
      <p>Enough to power <strong>5,800 homes</strong> for an entire year</p>
    </div>
  </div>
  <div class="visual-scale" role="img" aria-label="Visual bar showing 47,500 tons compared to city of 100,000 people's annual output of 900,000 tons">
    <div class="bar yours" style="width: 5.3%"></div>
    <div class="bar city" style="width: 100%"></div>
    <p class="caption">Your reduction vs. annual emissions of a city of 100,000</p>
  </div>
</div>`,
        explanation:
          'Rather than leaving "47,500 metric tons" as an abstract number, the design provides three different human-scale analogies that users can visualize. Cars, trees, and homes are tangible objects people can picture, making the magnitude meaningful.',
        principle:
          'Human-scale analogies overcome scope insensitivity by mapping abstract quantities to familiar, imageable objects',
        metrics: {
          before: '18% of employees could estimate their company\'s impact magnitude',
          after: '67% could estimate impact magnitude after concrete comparisons',
          improvement: '272% increase in magnitude comprehension',
        },
      },
      {
        title: 'Per-Unit Donation Impact with Visual Scaling',
        description:
          'Charity donation page breaking abstract totals into tangible per-unit contributions',
        code: `<form class="donation-form">
  <h3>Provide Clean Water</h3>
  <div class="amount-selector">
    <button class="amount" data-value="25">
      <span class="price">$25</span>
      <span class="impact">1 family for 1 month</span>
      <img src="family-1.jpg" alt="A family of four with clean water">
    </button>
    <button class="amount selected" data-value="100">
      <span class="price">$100</span>
      <span class="impact">4 families for 1 month</span>
      <div class="family-grid">
        <img src="family-1.jpg" alt="">
        <img src="family-2.jpg" alt="">
        <img src="family-3.jpg" alt="">
        <img src="family-4.jpg" alt="">
      </div>
    </button>
    <button class="amount" data-value="500">
      <span class="price">$500</span>
      <span class="impact">A classroom of 30 children for 1 year</span>
      <img src="classroom.jpg" alt="A classroom of children">
    </button>
  </div>
  <p class="total-context">Together, our donors have provided clean water
    to <strong>the equivalent of every person in Portland, Oregon</strong>.</p>
</form>`,
        explanation:
          'Each donation tier shows a concrete, identifiable unit of impact. Photos ground each tier in reality. The total impact is expressed as a city-sized comparison rather than an abstract number, helping donors grasp the cumulative scope.',
        principle:
          'Per-unit impact with identifiable recipients defeats scope insensitivity by keeping each increment tangible',
        metrics: {
          before: 'Average donation: $45 with abstract "helps thousands" messaging',
          after: 'Average donation: $78 with per-unit concrete impact framing',
          improvement: '73% increase in average donation amount',
        },
      },
      {
        title: 'Progressive Scale Dashboard with Magnitude Breakpoints',
        description:
          'Analytics dashboard that communicates metric magnitude through visual scaling and contextual benchmarks',
        code: `<div class="metric-card">
  <h4>Monthly Active Users</h4>
  <div class="metric-value">
    <span class="number">2.4M</span>
    <span class="trend positive">+340K this month</span>
  </div>
  <div class="magnitude-context">
    <div class="benchmark">
      <span class="label">That's more than the population of</span>
      <span class="comparison">Houston, TX</span>
    </div>
    <div class="growth-context">
      <span class="label">Growth this month equals</span>
      <span class="comparison">the entire city of Tampa, FL</span>
    </div>
  </div>
  <div class="scale-bar" role="img" aria-label="Progress bar showing 2.4 million out of 10 million goal, 24% complete">
    <div class="filled" style="width: 24%">
      <span class="milestone" style="left: 4.2%">100K</span>
      <span class="milestone" style="left: 42%">1M</span>
    </div>
    <span class="goal">10M goal</span>
  </div>
</div>`,
        explanation:
          'The dashboard doesn\'t just show "2.4M"—it maps the number to a city population, contextualizes the growth in the same way, and provides a visual scale bar with milestones. Users can feel the magnitude because they can picture Houston.',
        principle:
          'Layered magnitude context (comparison + visual scale + benchmarks) builds intuitive understanding of large numbers',
      },
    ],

    bad: [
      {
        title: 'Abstract Large Numbers Without Context',
        description:
          'Dashboard displaying raw metrics with no magnitude context or reference points',
        code: `<!-- DON'T DO THIS -->
<div class="dashboard">
  <div class="metric-card">
    <h4>Total Users</h4>
    <span class="number">4,283,917</span>
  </div>
  <div class="metric-card">
    <h4>API Calls</h4>
    <span class="number">892,471,203</span>
  </div>
  <div class="metric-card">
    <h4>Data Processed</h4>
    <span class="number">14.7 PB</span>
  </div>
  <div class="metric-card">
    <h4>Revenue</h4>
    <span class="number">$28,491,002</span>
  </div>
</div>`,
        explanation:
          'Raw numbers at this scale are meaningless to human intuition. Users cannot tell whether 892 million API calls is good or bad, growing or shrinking, large or small relative to capacity. Every metric looks equally impressive and equally incomprehensible.',
        principle:
          'Large numbers without reference points exploit scope insensitivity—they impress without informing',
      },
      {
        title: 'Unscaled Impact Display for Charity',
        description:
          'Nonprofit impact page using abstract statistics that trigger scope insensitivity',
        code: `<!-- DON'T DO THIS -->
<section class="impact-page">
  <h2>Our Global Impact</h2>
  <div class="stats-grid">
    <div class="stat">
      <span class="number">5,000,000</span>
      <span class="label">Lives Touched</span>
    </div>
    <div class="stat">
      <span class="number">120</span>
      <span class="label">Countries</span>
    </div>
    <div class="stat">
      <span class="number">$2.3B</span>
      <span class="label">Distributed</span>
    </div>
  </div>
  <p>Help us reach even more people around the world.</p>
  <button>Donate Now</button>
</section>`,
        explanation:
          'Five million "lives touched" generates the same emotional response as fifty thousand. The abstract statistics fail to convey magnitude—users form a prototype of "helping one person" and that feeling doesn\'t scale. No concrete analogy, no identifiable individuals, no tangible unit of impact.',
        principle:
          'Abstract statistics at massive scale fail to motivate because emotional response saturates at small numbers',
      },
      {
        title: 'Identical Visual Treatment Across Magnitudes',
        description:
          'Alert system using the same badge style for vastly different quantities',
        code: `<!-- DON'T DO THIS -->
<div class="alerts">
  <div class="alert-badge warning">
    <span class="count">3</span>
    <span class="label">Low-priority issues</span>
  </div>
  <div class="alert-badge warning">
    <span class="count">3,847</span>
    <span class="label">Failed transactions</span>
  </div>
  <div class="alert-badge warning">
    <span class="count">12</span>
    <span class="label">Pending reviews</span>
  </div>
</div>`,
        explanation:
          'Using identical yellow warning badges for 3 issues and 3,847 failed transactions treats them as equivalently important. The visual prototype (yellow badge) generates the same response regardless of the 1,000x difference in magnitude. Users will likely triage these with equal urgency.',
        principle:
          'Identical visual treatment across different magnitudes reinforces scope insensitivity instead of counteracting it',
      },
    ],

    realWorld: [
      {
        company: 'Charity: Water',
        product: 'Donation and Impact Pages',
        url: 'https://www.charitywater.org',
        description:
          'Charity: Water breaks donations into per-person cost ($40 = clean water for one person) and uses individual stories with names and photos. Their impact page shows specific wells, specific villages, and GPS coordinates—making each unit of impact identifiable and concrete.',
        effectiveness: 'very-effective',
        analysis:
          'By grounding each donation in an identifiable person and specific location, Charity: Water defeats scope insensitivity. Donors feel connected to individual impact units rather than drowning in abstract millions. This approach has raised over $700M by making every dollar feel tangible.',
      },
      {
        company: 'The New York Times',
        product: 'COVID-19 Data Journalism',
        url: 'https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html',
        description:
          'The NYT COVID dashboard used visual scaling techniques: each dot represented one death, animated to fill the screen progressively. Headlines translated numbers into comparisons: "More Americans have now died than in the Vietnam War."',
        effectiveness: 'very-effective',
        analysis:
          'By mapping abstract death tolls to familiar reference points (wars, cities, stadiums) and using visual accumulation animations, the NYT made the accelerating scope of the pandemic viscerally real. This approach helped readers grasp magnitude changes that raw numbers could not convey.',
      },
      {
        company: 'Stripe',
        product: 'Dashboard Analytics',
        url: 'https://dashboard.stripe.com',
        description:
          'Stripe\'s dashboard shows payment volume with contextual benchmarks: growth percentage, comparison to previous period, and trend sparklines. Large numbers are always accompanied by relative indicators that help merchants understand magnitude.',
        effectiveness: 'effective',
        analysis:
          'Rather than showing raw transaction counts, Stripe contextualizes every metric with trend data and period comparisons. This helps merchants distinguish between a "big day" and a "normal day" even when both involve thousands of transactions.',
      },
      {
        company: 'Our World in Data',
        product: 'Global Statistics Visualizations',
        url: 'https://ourworldindata.org',
        description:
          'Our World in Data uses interactive charts with logarithmic scales, per-capita normalization, and direct country comparisons to make global-scale data comprehensible. Users can toggle between absolute and relative views.',
        effectiveness: 'very-effective',
        analysis:
          'By allowing users to switch between per-capita and absolute views, zoom into specific time ranges, and compare directly between countries, the platform actively counteracts scope insensitivity. Users build genuine intuition for global-scale quantities through interactive exploration.',
      },
    ],

    abTests: [
      {
        title: 'Donation Page: Abstract Impact vs Concrete Per-Unit Impact',
        hypothesis:
          'Showing concrete per-unit impact with identifiable beneficiaries will increase donation amounts compared to abstract aggregate statistics',
        controlVersion: {
          description:
            'Donation page showing aggregate impact: "Your donation helps provide clean water to communities in need. Last year we helped 2.3 million people across 47 countries."',
          metrics: {
            conversionRate: '3.8%',
            averageDonation: '$42',
            timeOnPage: '1:45',
          },
        },
        treatmentVersion: {
          description:
            'Donation page with per-unit impact: "$25 = clean water for one family. Meet the Abara family in Nigeria who received clean water last month." Each tier shows specific beneficiary photos and stories.',
          metrics: {
            conversionRate: '5.9%',
            averageDonation: '$71',
            timeOnPage: '3:22',
          },
        },
        results: {
          winner: 'treatment',
          analysis:
            'Concrete per-unit impact increased donations by 69% and conversion rate by 55%. Users spent nearly twice as long on the page, engaging with individual stories. The identifiable victim effect and tangible per-unit framing overcame scope insensitivity that made "2.3 million people" feel abstract.',
          learnings: [
            'Per-unit concrete impact dramatically outperforms abstract aggregate statistics for driving donations',
            'Identifiable individuals with names and photos generate far more empathy than anonymous millions',
            'Users chose higher donation tiers when they could visualize the incremental impact of each tier',
            'Combining individual stories with aggregate context ("Together, we\'ve reached 2.3M people") works better than either alone',
          ],
        },
      },
      {
        title: 'Dashboard Metrics: Raw Numbers vs Contextual Magnitude',
        hypothesis:
          'Adding human-scale comparisons and magnitude context to dashboard metrics will improve user decision-making accuracy',
        controlVersion: {
          description:
            'Analytics dashboard showing raw metrics: "Monthly Active Users: 2,400,000", "API Calls: 892M", "Revenue: $28.5M"',
          metrics: {
            decisionAccuracy: '34%',
            timeToInsight: '4:12',
            userConfidence: '5.2/10',
          },
        },
        treatmentVersion: {
          description:
            'Dashboard with magnitude context: "2.4M MAU (larger than Houston, TX)", trend sparklines, growth comparisons to previous periods, and benchmark indicators showing where metrics fall relative to industry averages',
          metrics: {
            decisionAccuracy: '61%',
            timeToInsight: '2:38',
            userConfidence: '7.8/10',
          },
        },
        results: {
          winner: 'treatment',
          analysis:
            'Contextual magnitude improved decision accuracy by 79% and reduced time to insight by 37%. Users reported significantly higher confidence in their interpretations. The human-scale comparisons helped users build mental models for numbers they otherwise couldn\'t intuit.',
          learnings: [
            'Raw large numbers are effectively meaningless without magnitude context',
            'City population comparisons were the most intuitive reference point for user counts',
            'Trend data (growth rate, direction) mattered more than absolute numbers for decision-making',
            'Users who could toggle between absolute and relative views made the best decisions',
          ],
        },
      },
    ],
  },

  //===========================================
  // DETECTION
  //===========================================
  detection: {
    visualCues: [
      {
        name: 'Unscaled Large Numbers',
        description:
          'Dashboard metrics or statistics displaying large numbers (thousands, millions, billions) without contextual reference points',
        howToSpot:
          'Look for raw numbers above 10,000 displayed without comparisons, benchmarks, or human-scale analogies',
        severity: ImpactLevel.HIGH,
      },
      {
        name: 'Uniform Visual Weight Across Magnitudes',
        description:
          'Badges, cards, or indicators that use identical visual treatment for quantities differing by orders of magnitude',
        howToSpot:
          'Check if a "3 issues" badge looks identical to a "3,000 issues" badge—same size, color, and prominence',
        severity: ImpactLevel.HIGH,
      },
      {
        name: 'Abstract Impact Statements',
        description:
          'Phrases like "millions of users" or "billions of data points" without tangible comparisons',
        howToSpot:
          'Look for large aggregate numbers in marketing copy, impact pages, or dashboards without human-scale translation',
        severity: ImpactLevel.MEDIUM,
      },
      {
        name: 'Linear Scales for Exponential Data',
        description:
          'Charts plotting data with 100x+ variance on linear axes, making small values invisible',
        howToSpot:
          'Check if chart axes show values ranging across multiple orders of magnitude on a linear scale',
        severity: ImpactLevel.HIGH,
      },
      {
        name: 'Missing Benchmark Context',
        description:
          'Metrics displayed without industry benchmarks, historical comparisons, or goal progress indicators',
        howToSpot:
          'Look for standalone numbers without "compared to" language, trend arrows, or progress bars',
        severity: ImpactLevel.MEDIUM,
      },
    ],

    patterns: [
      {
        name: 'Raw Magnitude Display Pattern',
        description: 'Large numbers presented without contextual reference, comparisons, or human-scale translation',
        indicators: [
          'Numbers above 10,000 with no comparison text nearby',
          'Metric cards showing only absolute values',
          'Statistics pages with just numbers and labels',
          'Impact sections using only aggregate totals',
        ],
        severity: ImpactLevel.HIGH,
        confidence: 'high',
      },
      {
        name: 'Flat Visual Hierarchy Pattern',
        description: 'Multiple metrics with vastly different magnitudes displayed with identical visual treatment',
        indicators: [
          'Same-sized cards for metrics ranging from dozens to millions',
          'Uniform badge styling regardless of quantity',
          'Equal whitespace and emphasis for metrics of different magnitudes',
          'No color or size scaling based on magnitude',
        ],
        severity: ImpactLevel.HIGH,
        confidence: 'high',
      },
      {
        name: 'Abstract Statistics Pattern',
        description: 'Aggregate statistics presented without individual stories, concrete analogies, or tangible units',
        indicators: [
          '"X million people" without per-person or per-unit breakdown',
          'Impact pages with only big numbers and no human stories',
          'Cumulative counters with no intermediate milestones',
          'Financial figures without per-user or per-unit translation',
        ],
        severity: ImpactLevel.CRITICAL,
        confidence: 'high',
      },
      {
        name: 'Scale Blindness Pattern',
        description: 'Visualizations or interfaces that fail to communicate the difference between 10x, 100x, or 1000x changes',
        indicators: [
          'Charts where 10% and 1000% changes look similar',
          'Notification counts that max out at "99+"',
          'Progress bars that show 50% and 5% with similar visual weight',
          'Percentage changes without absolute number context',
        ],
        severity: ImpactLevel.MEDIUM,
        confidence: 'medium',
      },
    ],

    checklistQuestions: [
      'Are large numbers (10K+) accompanied by human-scale comparisons or analogies?',
      'Do metrics of different magnitudes have proportionally different visual treatment?',
      'Are there concrete per-unit breakdowns for aggregate statistics?',
      'Do data visualizations use appropriate scales for the data range (logarithmic for exponential data)?',
      'Are identifiable individuals or stories used alongside abstract statistics?',
      'Do dashboards provide benchmarks, trends, or goals alongside raw numbers?',
      'Can users easily perceive the difference between a 10x and 100x change?',
      'Are impact statements translated into tangible, imageable terms?',
      'Do alert systems scale their visual urgency with the magnitude of the issue?',
      'Are accessibility alternatives provided that communicate magnitude through non-visual means?',
    ],
  },

  //===========================================
  // AI INTENT
  //===========================================
  intent: {
    systemPrompt: `You are an expert in cognitive psychology and UX design, specializing in scope insensitivity (scope neglect).

Analyze the provided design for scope insensitivity patterns. Identify:

1. **Raw Magnitude Displays**: Large numbers shown without human-scale context or reference points
2. **Flat Visual Hierarchy**: Identical visual treatment for metrics or alerts differing by orders of magnitude
3. **Abstract Impact Communication**: Aggregate statistics without per-unit breakdowns or identifiable beneficiaries
4. **Scale Communication**: How well visualizations communicate the difference between 10x, 100x, and 1000x changes
5. **Contextual Benchmarks**: Whether metrics include comparisons, trends, or goal progress

For each pattern found:
- Identify what magnitude is being communicated (or failing to be communicated)
- Assess whether users can intuitively grasp the scale
- Determine if the design counteracts or reinforces scope insensitivity
- Evaluate whether magnitude context is accessible to all users
- Suggest concrete improvements using human-scale analogies, visual scaling, or per-unit breakdowns

Consider:
- Are large numbers made tangible through familiar comparisons (cities, objects, time periods)?
- Do visualizations use appropriate scales for the data range?
- Are aggregate statistics broken into comprehensible per-unit impacts?
- Do alert systems proportionally convey urgency based on magnitude?
- Can screen reader users perceive magnitude differences?

Provide actionable recommendations for making scale and magnitude genuinely comprehensible.`,

    outputSchema: {
      type: 'object',
      properties: {
        scopePatterns: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              type: { type: 'string' },
              location: { type: 'string' },
              magnitude: { type: 'string' },
              currentCommunication: { type: 'string' },
              scaleComprehension: { type: 'string' },
              recommendation: { type: 'string' },
            },
            required: [
              'type',
              'location',
              'magnitude',
              'currentCommunication',
              'scaleComprehension',
            ],
          },
        },
        overallAssessment: {
          type: 'object',
          properties: {
            magnitudeClarity: { type: 'number' },
            visualScaling: { type: 'number' },
            contextualBenchmarks: { type: 'number' },
            humanScaleAnalogies: { type: 'number' },
          },
          required: [
            'magnitudeClarity',
            'visualScaling',
            'contextualBenchmarks',
            'humanScaleAnalogies',
          ],
        },
        recommendations: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              priority: { type: 'number' },
              title: { type: 'string' },
              description: { type: 'string' },
              expectedImpact: { type: 'string' },
            },
            required: ['priority', 'title', 'description'],
          },
        },
      },
      required: [
        'scopePatterns',
        'overallAssessment',
        'recommendations',
      ],
    },
  },

  //===========================================
  // GUIDELINES
  //===========================================
  guidelines: {
    implementation: [
      {
        step: 1,
        title: 'Identify Magnitude-Sensitive Content',
        description:
          'Audit your interface for numbers, statistics, and quantities where the magnitude matters for user understanding and decision-making',
        example:
          'Map all metrics above 10,000, all impact statistics, all data visualizations with wide ranges, and all financial or quantity displays',
        tips: [
          'Pay special attention to numbers above 100,000 where human intuition fails most',
          'Include both absolute numbers and rates/percentages that imply large absolute quantities',
          'Don\'t forget text content—"millions of users" is just as scope-insensitive as a raw number',
        ],
      },
      {
        step: 2,
        title: 'Create Human-Scale Analogies',
        description:
          'Develop a library of concrete, familiar comparisons for the magnitude ranges your product uses',
        example:
          'For user counts: 10K = small town, 100K = medium city, 1M = metropolitan area. For data: 1TB = 250,000 photos, 1PB = every book ever written 10x over.',
        tips: [
          'Use comparisons your specific audience will find intuitive',
          'Keep analogies culturally appropriate and geographically relevant',
          'Update analogies as magnitudes change—yesterday\'s "wow" is today\'s baseline',
        ],
      },
      {
        step: 3,
        title: 'Design Proportional Visual Indicators',
        description:
          'Ensure visual treatment—size, color, urgency, animation—scales with magnitude',
        example:
          'Alert badges: 1-10 = small gray, 11-100 = medium yellow, 100-1000 = large orange, 1000+ = extra-large red with pulse animation',
        tips: [
          'Use stepped thresholds rather than continuous scaling (humans perceive steps better)',
          'Ensure color scaling meets accessibility requirements at all steps',
          'Test that the visual difference between magnitude levels is perceptible to users',
        ],
      },
      {
        step: 4,
        title: 'Add Contextual Benchmarks',
        description:
          'Provide reference points that help users calibrate: trends, goals, industry averages, or historical comparisons',
        example:
          'Instead of just "2.4M users", show "2.4M users (up 340K from last month, 85% of industry leader)"',
        tips: [
          'Trends (growth, decline) often matter more than absolute numbers',
          'Goal progress indicators make large numbers meaningful relative to targets',
          'Historical context prevents recency bias in magnitude interpretation',
        ],
      },
      {
        step: 5,
        title: 'Test Magnitude Comprehension',
        description:
          'Validate that users can accurately estimate relative magnitudes after viewing your interface',
        example:
          'Show users the dashboard, then ask: "Which metric changed the most? Is 2.4M users a lot for a company like this? How much bigger is metric A than metric B?"',
        tips: [
          'Test with users unfamiliar with your domain—they reveal scope insensitivity most clearly',
          'Compare comprehension scores between raw numbers and contextualized displays',
          'Iterate on analogies based on which ones users actually find helpful',
        ],
      },
    ],

    dos: [
      'Provide human-scale analogies for numbers above 10,000 (cities, objects, time periods)',
      'Use proportional visual treatment so magnitude differences are visible at a glance',
      'Break aggregate statistics into concrete per-unit impacts that users can picture',
      'Include trend context, benchmarks, and goals alongside absolute numbers',
      'Use identifiable individuals and stories alongside statistical aggregates',
      'Design data visualizations with appropriate scales for the data range',
      'Add interactive zoom or drill-down so users can explore magnitude levels',
      'Communicate magnitude through multiple channels (visual, textual, interactive)',
    ],

    donts: [
      'Don\'t display raw numbers above 10,000 without any reference point or comparison',
      'Don\'t use identical visual treatment for quantities differing by orders of magnitude',
      'Don\'t rely solely on abstract statistics to communicate impact or urgency',
      'Don\'t plot exponential data on linear scales without clear justification',
      'Don\'t assume users can intuitively distinguish between millions and billions',
      'Don\'t exploit scope insensitivity to minimize negative impacts or inflate trivial ones',
      'Don\'t use only aggregate totals when per-unit breakdowns would be more meaningful',
      'Don\'t neglect magnitude communication in accessibility alternatives (alt text, ARIA labels)',
    ],

    bestPractices: [
      {
        title: 'The Analogy Library Pattern',
        description:
          'Maintain a standardized set of human-scale comparisons for your product\'s key magnitude ranges',
        rationale:
          'Consistent analogies build shared mental models across your user base and reduce cognitive load',
        example:
          'User counts: "town" (10K), "city" (100K), "metro area" (1M), "country" (100M). Data: "photo album" (1GB), "library" (1TB), "Library of Congress" (10PB).',
      },
      {
        title: 'Magnitude-Proportional Alerts',
        description:
          'Scale alert visual urgency (size, color, animation) proportionally with the quantity or severity they represent',
        rationale:
          'Users rely on visual cues more than numbers; identical badges for 5 and 5,000 issues will receive identical triage priority',
        example:
          'Use a stepped scale: info (blue, small) < warning (yellow, medium) < critical (orange, large) < emergency (red, XL, pulsing), with thresholds tuned to your domain',
      },
      {
        title: 'Concrete-First, Abstract-Second',
        description:
          'Lead with tangible, imageable information and follow with precise statistics for those who want them',
        rationale:
          'Concrete framing is processed faster and remembered longer than abstract numbers',
        example:
          'Lead: "Enough clean water for every student in Chicago." Follow: "Precisely 471,000 students across 634 schools."',
      },
      {
        title: 'Interactive Magnitude Exploration',
        description:
          'Let users zoom, filter, and drill down through magnitude levels to build scale intuition',
        rationale:
          'Active exploration of scale builds deeper understanding than passive display',
        example:
          'Map visualization: click to zoom from global (billions) to country (millions) to city (thousands) to neighborhood (hundreds)',
      },
      {
        title: 'Logarithmic Thinking Tools',
        description:
          'When data spans multiple orders of magnitude, provide logarithmic views alongside linear ones',
        rationale:
          'Human perception is roughly logarithmic, but most charts default to linear scales that hide important patterns',
        example:
          'Toggle between linear and log scales on charts; use "power of 10" breakpoints on sliders and filters',
      },
    ],

    accessibility: [
      {
        wcagLevel: 'AA',
        criterion: '1.1.1',
        guideline:
          'Non-text Content - Provide text alternatives that communicate magnitude for visual scale representations',
        implementation:
          'Alt text for scaled visualizations must describe relative magnitude, not just data values. E.g., "Bar chart showing revenue 10x larger in Q4 than Q1" rather than just listing numbers.',
      },
      {
        wcagLevel: 'AA',
        criterion: '1.3.1',
        guideline:
          'Info and Relationships - Ensure magnitude relationships are programmatically determinable',
        implementation:
          'Use ARIA labels that include magnitude context: aria-label="3,847 failed transactions - critical severity, 100 times above normal baseline"',
      },
      {
        wcagLevel: 'AA',
        criterion: '1.4.1',
        guideline:
          'Use of Color - Don\'t rely solely on color to convey magnitude differences',
        implementation:
          'Combine color intensity with text labels, icons, size differences, and ARIA attributes so magnitude is perceivable without color vision',
      },
      {
        wcagLevel: 'AA',
        criterion: '2.4.6',
        guideline:
          'Headings and Labels - Use descriptive headings that include magnitude context',
        implementation:
          'Section headings should hint at scale: "2.4 Million Monthly Active Users" rather than just "Users" — giving screen reader users immediate magnitude context',
      },
    ],

    ethics: [
      {
        concern: 'Minimizing Harm Through Scope Insensitivity',
        severity: 'critical',
        explanation:
          'Deliberately presenting harmful impacts as abstract large numbers to exploit scope insensitivity and make them seem less concerning',
        mitigation:
          'Always provide concrete, human-scale translations for negative impacts. If 50,000 users were affected, say "everyone in a town the size of Sedona, AZ was impacted."',
      },
      {
        concern: 'Inflating Trivial Metrics',
        severity: 'high',
        explanation:
          'Using scaling techniques to make small, insignificant quantities appear larger and more impressive than they are',
        mitigation:
          'Apply the same scaling and contextualization standards to positive and negative metrics. Provide honest benchmarks.',
      },
      {
        concern: 'Identifiable Victim Exploitation',
        severity: 'high',
        explanation:
          'Using individual stories to drive emotional donations while obscuring how aggregate funds are allocated',
        mitigation:
          'Pair individual stories with transparent reporting on fund allocation, overhead, and aggregate outcomes. Don\'t use stories as emotional manipulation.',
      },
      {
        concern: 'Selective Magnitude Context',
        severity: 'medium',
        explanation:
          'Providing human-scale analogies only for metrics that benefit the organization while leaving unfavorable metrics as abstract numbers',
        mitigation:
          'Apply consistent magnitude communication standards across all metrics, favorable and unfavorable alike.',
      },
    ],
  },

  //===========================================
  // RESOURCES
  //===========================================
  resources: {
    papers: [
      {
        title: 'Insensitivity to the Value of Human Life: A Study of Psychophysical Numbing',
        author: 'Fetherstonhaugh, D., Slovic, P., Johnson, S. M., & Friedrich, J.',
        year: 1997,
        doi: '10.1006/jesp.1997.1334',
        description:
          'Key study demonstrating that the value of saving lives decreases as the number at risk increases',
        type: 'foundational',
      },
      {
        title: 'Measuring Nonuse Damages Using Contingent Valuation',
        author: 'Desvousges, W. H., Johnson, F. R., Dunford, R. W., Boyle, K. J., Hudson, S. P., & Wilson, K. N.',
        year: 1993,
        description:
          'The landmark migratory bird study showing willingness to pay barely changed across 2,000, 20,000, and 200,000 birds',
        type: 'foundational',
      },
      {
        title: 'Economic Preferences or Attitude Expressions? An Analysis of Dollar Responses to Public Issues',
        author: 'Kahneman, D., & Ritov, I.',
        year: 1994,
        doi: '10.1007/BF01065681',
        description:
          'Analysis showing that dollar valuations of public goods reflect attitudes toward prototypes rather than economic preferences for scope',
        type: 'foundational',
      },
      {
        title: 'If I Look at the Mass I Will Never Act: Psychic Numbing and Genocide',
        author: 'Slovic, P.',
        year: 2007,
        doi: '10.1080/17405620701615606',
        description:
          'Examines how scope insensitivity and psychic numbing contribute to inaction in the face of mass atrocities',
        type: 'advanced',
      },
    ],

    books: [
      {
        title: 'Thinking, Fast and Slow',
        author: 'Kahneman, Daniel',
        year: 2011,
        isbn: '9780374275631',
        description:
          'Covers scope insensitivity as part of the substitution heuristic—evaluating a prototype instead of the full scope',
        type: 'foundational',
      },
      {
        title: 'Numbers and Nerves: Information, Emotion, and Meaning in a World of Data',
        author: 'Slovic, P., & Slovic, S.',
        year: 2015,
        isbn: '9780870716751',
        description:
          'Explores how numbers fail to communicate meaning and how to bridge the gap between statistics and feeling',
        type: 'practical',
      },
      {
        title: 'Rationality: From AI to Zombies',
        author: 'Yudkowsky, Eliezer',
        year: 2015,
        description:
          'Detailed treatment of scope insensitivity with clear examples and implications for rational decision-making',
        type: 'practical',
      },
    ],

    articles: [
      {
        title: 'Scope Insensitivity',
        author: 'Yudkowsky, Eliezer',
        url: 'https://www.lesswrong.com/posts/2ftJ38y9SRBCBsCzy/scope-insensitivity',
        description:
          'Accessible introduction to scope insensitivity with the classic bird-saving example and practical implications',
        type: 'foundational',
      },
      {
        title: 'Making Data Meaningful: A Guide to Presenting Statistics',
        author: 'UNECE',
        url: 'https://unece.org/statistics/publications/making-data-meaningful',
        description:
          'Practical guidelines for communicating statistical magnitude to general audiences',
        type: 'practical',
      },
    ],

    videos: [
      {
        title: 'The Science of Thinking Big: Why We Ignore Large Numbers',
        author: 'Veritasium',
        url: 'https://www.youtube.com/watch?v=8YUWDrLazCg',
        description:
          'Video exploration of why human brains struggle with large numbers and scope',
        type: 'foundational',
      },
    ],

    demos: [
      {
        title: 'How Much is a Billion?',
        author: 'Neal Agarwal',
        url: 'https://neal.fun/spend/',
        description:
          'Interactive visualization that makes the magnitude of a billion dollars tangible through spending simulations',
        type: 'practical',
      },
    ],
  },

  //===========================================
  // RELATIONSHIPS
  //===========================================
  relationships: {
    complements: [
      'anchoring-bias', // Anchors can set magnitude reference points
      'framing-effect', // How magnitude is framed determines perceived impact
      'identifiable-victim-effect', // Individual stories counteract scope insensitivity
      'availability-heuristic', // Vivid examples at any scale override statistical scope
    ],

    conflicts: [
      'proportionality-bias', // People expect proportional responses but can't feel proportional scope
      'anchoring-bias', // Strong anchors can override scope by fixing a reference point
    ],

    confusedWith: [
      'psychic-numbing', // Related but more specific: emotional shutdown at large scale
      'compassion-fatigue', // Reduced empathy from repeated exposure, not magnitude
      'base-rate-neglect', // Ignoring frequency data, not magnitude data
    ],

    hierarchy: {
      parent: 'cognitive-bias',
      children: [
        'psychic-numbing',
        'proportion-dominance',
      ],
    },
  },
};
