/**
 * Curated palette library for @cognivo/theme-generator.
 *
 * Each palette is a hand-picked set of 8 hex values designed to look
 * professional out-of-the-box. `keywords` drive the fuzzy match in compose.ts.
 *
 * Zero external dependencies — all colors are literal hex strings.
 */

export interface Palette {
  /** Primary action color — buttons, links, focus rings. */
  primary: string;
  /** Secondary accent, works next to primary. */
  secondary: string;
  /** Pop/highlight color — chart accents, badges. */
  accent: string;
  /** Page background. */
  background: string;
  /** Elevated surface (cards, containers). */
  surface: string;
  /** Default text color. */
  text: string;
  /** Muted/low-emphasis text. */
  muted: string;
  /** Divider / default border. */
  border: string;
  /** Descriptors that boost this palette's score. */
  keywords: string[];
  /** Base weight — use to favor or penalize a palette. */
  weight: number;
  /** True when this palette is designed for a dark background. */
  dark?: boolean;
}

export const PALETTES: Record<string, Palette> = {
  'ocean-professional': {
    primary: '#0066cc',
    secondary: '#00a8d9',
    accent: '#00d4ff',
    background: '#ffffff',
    surface: '#f0f7ff',
    text: '#0a2540',
    muted: '#546e7a',
    border: '#d0e3f0',
    keywords: ['ocean', 'blue', 'professional', 'trust', 'corporate', 'clean', 'cool', 'marine'],
    weight: 1.0,
  },
  'forest-calm': {
    primary: '#2d6a4f',
    secondary: '#52b788',
    accent: '#95d5b2',
    background: '#f8fbf9',
    surface: '#eef4f0',
    text: '#1b2e25',
    muted: '#5c6f66',
    border: '#c9dcd2',
    keywords: ['forest', 'green', 'calm', 'natural', 'organic', 'eco', 'nature', 'tree'],
    weight: 1.0,
  },
  'sunset-warm': {
    primary: '#e76f51',
    secondary: '#f4a261',
    accent: '#e9c46a',
    background: '#fffaf5',
    surface: '#fff1e6',
    text: '#2b1810',
    muted: '#7a5c4a',
    border: '#f0d9c7',
    keywords: ['sunset', 'warm', 'orange', 'friendly', 'cozy', 'inviting', 'amber', 'dusk'],
    weight: 1.0,
  },
  'midnight-tech': {
    primary: '#5e60ce',
    secondary: '#64dfdf',
    accent: '#a594f9',
    background: '#0a0a14',
    surface: '#141425',
    text: '#eaeaf0',
    muted: '#8888a5',
    border: '#2a2a3f',
    keywords: ['midnight', 'dark', 'tech', 'futuristic', 'purple', 'night', 'space'],
    weight: 1.0,
    dark: true,
  },
  'arctic-minimal': {
    primary: '#1b4965',
    secondary: '#62b6cb',
    accent: '#bee9e8',
    background: '#ffffff',
    surface: '#f5fafd',
    text: '#102a43',
    muted: '#627d98',
    border: '#d9e2ec',
    keywords: ['arctic', 'cold', 'minimal', 'ice', 'crisp', 'nordic', 'winter', 'clean'],
    weight: 1.0,
  },
  'desert-earthy': {
    primary: '#a0522d',
    secondary: '#cd853f',
    accent: '#deb887',
    background: '#faf5ee',
    surface: '#f2e8d5',
    text: '#3d2817',
    muted: '#8b6f4e',
    border: '#d8c4a3',
    keywords: ['desert', 'earthy', 'sand', 'terracotta', 'clay', 'dune', 'warm', 'brown'],
    weight: 1.0,
  },
  'lavender-soft': {
    primary: '#8b7fd1',
    secondary: '#b5a8e0',
    accent: '#d4c5f9',
    background: '#fbf9ff',
    surface: '#f3eefc',
    text: '#2e1f4f',
    muted: '#766690',
    border: '#e1d7f0',
    keywords: ['lavender', 'soft', 'purple', 'gentle', 'dreamy', 'romantic', 'pastel'],
    weight: 1.0,
  },
  'rose-editorial': {
    primary: '#c8576e',
    secondary: '#e4919c',
    accent: '#f4c2c2',
    background: '#fffafc',
    surface: '#fdeff2',
    text: '#2b1018',
    muted: '#8a5966',
    border: '#f0d4da',
    keywords: ['rose', 'editorial', 'pink', 'magazine', 'elegant', 'romantic', 'feminine'],
    weight: 1.0,
  },
  'sage-natural': {
    primary: '#87a878',
    secondary: '#b5c9a6',
    accent: '#d9e4cb',
    background: '#fafbf7',
    surface: '#f0f3ea',
    text: '#2a3524',
    muted: '#6b7962',
    border: '#d2dcc4',
    keywords: ['sage', 'natural', 'herb', 'organic', 'muted', 'green', 'earthy', 'calm'],
    weight: 1.0,
  },
  'cyberpunk-neon': {
    primary: '#ff00aa',
    secondary: '#00fff0',
    accent: '#ffe600',
    background: '#05020f',
    surface: '#130825',
    text: '#f5e6ff',
    muted: '#8864a8',
    border: '#3a1a5c',
    keywords: ['cyberpunk', 'neon', 'dark', 'vibrant', 'futuristic', 'electric', 'cyber', 'retro'],
    weight: 1.0,
    dark: true,
  },
  'noir-luxurious': {
    primary: '#d4af37',
    secondary: '#b38728',
    accent: '#f1e5ac',
    background: '#0a0a0a',
    surface: '#1a1814',
    text: '#f5efd7',
    muted: '#8a7f65',
    border: '#2d2a22',
    keywords: ['noir', 'luxurious', 'luxury', 'gold', 'premium', 'elegant', 'dark', 'sophisticated'],
    weight: 1.0,
    dark: true,
  },
  'sunrise-energetic': {
    primary: '#ff6b35',
    secondary: '#ffb400',
    accent: '#ffd166',
    background: '#fffdf7',
    surface: '#fff4e0',
    text: '#2a1506',
    muted: '#8a6240',
    border: '#f6dcb2',
    keywords: ['sunrise', 'energetic', 'energy', 'vibrant', 'bright', 'morning', 'dawn', 'bold'],
    weight: 1.0,
  },
  'monochrome-minimal': {
    primary: '#111111',
    secondary: '#444444',
    accent: '#777777',
    background: '#ffffff',
    surface: '#f5f5f5',
    text: '#0a0a0a',
    muted: '#6a6a6a',
    border: '#e1e1e1',
    keywords: ['monochrome', 'minimal', 'minimalist', 'black', 'white', 'grayscale', 'simple', 'clean'],
    weight: 1.0,
  },
  'monochrome-minimal-dark': {
    primary: '#f5f5f5',
    secondary: '#c4c4c4',
    accent: '#8a8a8a',
    background: '#0c0c0c',
    surface: '#1a1a1a',
    text: '#f2f2f2',
    muted: '#9a9a9a',
    border: '#2a2a2a',
    keywords: ['monochrome', 'minimal', 'minimalist', 'dark', 'black', 'grayscale', 'simple'],
    weight: 1.0,
    dark: true,
  },
  'playful-candy': {
    primary: '#ff5da2',
    secondary: '#7ae1bf',
    accent: '#ffc857',
    background: '#fffafc',
    surface: '#ffeef5',
    text: '#3a1230',
    muted: '#955a7d',
    border: '#ffd6e5',
    keywords: ['playful', 'candy', 'fun', 'colorful', 'pink', 'sweet', 'joyful', 'kids'],
    weight: 1.0,
  },
  'muted-editorial': {
    primary: '#6b4e71',
    secondary: '#9e8aa0',
    accent: '#c9b8c2',
    background: '#fbf8f5',
    surface: '#f0ebe6',
    text: '#2a1e2c',
    muted: '#7a6b7d',
    border: '#ddd1cc',
    keywords: ['muted', 'editorial', 'magazine', 'sophisticated', 'subdued', 'refined', 'quiet'],
    weight: 1.0,
  },
  'bold-vibrant': {
    primary: '#e63946',
    secondary: '#1d3557',
    accent: '#ffd60a',
    background: '#ffffff',
    surface: '#f1faee',
    text: '#0a1a2f',
    muted: '#5d6d7e',
    border: '#a8dadc',
    keywords: ['bold', 'vibrant', 'red', 'strong', 'impact', 'statement', 'energetic'],
    weight: 1.0,
  },
  'pastel-friendly': {
    primary: '#a0c4ff',
    secondary: '#bdb2ff',
    accent: '#ffc6ff',
    background: '#ffffff',
    surface: '#fdfcff',
    text: '#2a2e4a',
    muted: '#7b7b9e',
    border: '#e4e8f5',
    keywords: ['pastel', 'friendly', 'soft', 'gentle', 'cute', 'light', 'approachable'],
    weight: 1.0,
  },
  'technical-sharp': {
    primary: '#00e5ff',
    secondary: '#7c4dff',
    accent: '#1de9b6',
    background: '#0d1117',
    surface: '#161b22',
    text: '#e6edf3',
    muted: '#7d8590',
    border: '#30363d',
    keywords: ['technical', 'sharp', 'tech', 'code', 'developer', 'cyber', 'dark', 'engineering'],
    weight: 1.0,
    dark: true,
  },
  'luxury-gold': {
    primary: '#b8860b',
    secondary: '#daa520',
    accent: '#f4e4a1',
    background: '#fffdf5',
    surface: '#faf3dd',
    text: '#2e2105',
    muted: '#876d2a',
    border: '#e6d9a8',
    keywords: ['luxury', 'gold', 'premium', 'exclusive', 'opulent', 'rich', 'elegant'],
    weight: 1.0,
  },
  'medical-clean': {
    primary: '#0077b6',
    secondary: '#00b4d8',
    accent: '#90e0ef',
    background: '#ffffff',
    surface: '#f5fbfd',
    text: '#03304f',
    muted: '#5a7a8f',
    border: '#d8ecf3',
    keywords: ['medical', 'clean', 'health', 'clinical', 'hospital', 'sterile', 'healthcare', 'blue'],
    weight: 1.0,
  },
  'fintech-trust': {
    primary: '#1b5e8a',
    secondary: '#2c7c9e',
    accent: '#4cb3d4',
    background: '#ffffff',
    surface: '#f4f7fa',
    text: '#0b1d2d',
    muted: '#4f6579',
    border: '#d4dde6',
    keywords: ['fintech', 'trust', 'finance', 'banking', 'money', 'secure', 'professional'],
    weight: 1.0,
  },
  'warm-neutral': {
    primary: '#8b6f47',
    secondary: '#b09173',
    accent: '#d4b896',
    background: '#faf7f2',
    surface: '#f1ebe0',
    text: '#2e2416',
    muted: '#7a6a54',
    border: '#ddd0bc',
    keywords: ['warm', 'neutral', 'beige', 'cream', 'natural', 'inviting', 'earthy'],
    weight: 1.0,
  },
  'cool-neutral': {
    primary: '#4a5c6e',
    secondary: '#6f8191',
    accent: '#9fb0be',
    background: '#fbfcfd',
    surface: '#eef2f5',
    text: '#1c2733',
    muted: '#5f6d7a',
    border: '#d4dbe2',
    keywords: ['cool', 'neutral', 'slate', 'gray', 'calm', 'professional', 'balanced'],
    weight: 1.0,
  },
  'vibrant-pop': {
    primary: '#ef476f',
    secondary: '#06d6a0',
    accent: '#ffd166',
    background: '#ffffff',
    surface: '#fdf7f2',
    text: '#111111',
    muted: '#6d6d6d',
    border: '#e6e6e6',
    keywords: ['vibrant', 'pop', 'colorful', 'bright', 'playful', 'energetic', 'bold'],
    weight: 1.0,
  },
  'earthy-natural': {
    primary: '#6b4423',
    secondary: '#9c6b3f',
    accent: '#c89b6c',
    background: '#faf6f0',
    surface: '#ede2d0',
    text: '#2a1a0c',
    muted: '#75604c',
    border: '#d4c3a8',
    keywords: ['earthy', 'natural', 'brown', 'organic', 'wood', 'rustic', 'grounded'],
    weight: 1.0,
  },
  'futuristic-chrome': {
    primary: '#4361ee',
    secondary: '#3a0ca3',
    accent: '#7209b7',
    background: '#fafbff',
    surface: '#eef0fa',
    text: '#10103a',
    muted: '#5c5d8a',
    border: '#d4d8ee',
    keywords: ['futuristic', 'chrome', 'future', 'sleek', 'modern', 'sci-fi', 'space-age'],
    weight: 1.0,
  },
  'paper-light': {
    primary: '#3a3a3a',
    secondary: '#6b6b6b',
    accent: '#a38560',
    background: '#fdfbf7',
    surface: '#f5f1e8',
    text: '#1a1a1a',
    muted: '#707070',
    border: '#e2ddd0',
    keywords: ['paper', 'light', 'print', 'newspaper', 'reading', 'book', 'bright'],
    weight: 1.0,
  },
  'ink-dark': {
    primary: '#7fb3d5',
    secondary: '#aed6f1',
    accent: '#d6eaf8',
    background: '#0d1321',
    surface: '#1d2d44',
    text: '#f0f3f7',
    muted: '#8d99ae',
    border: '#2d3f5c',
    keywords: ['ink', 'dark', 'deep', 'night', 'manuscript', 'dim', 'moody'],
    weight: 1.0,
    dark: true,
  },
  'scandinavian-minimal': {
    primary: '#4a6572',
    secondary: '#8da9b5',
    accent: '#f9aa33',
    background: '#fafaf9',
    surface: '#eef1ef',
    text: '#232d33',
    muted: '#5a6a72',
    border: '#d6dbd9',
    keywords: ['scandinavian', 'minimal', 'nordic', 'hygge', 'scandi', 'clean', 'simple', 'cozy'],
    weight: 1.0,
  },
  'japanese-zen': {
    primary: '#8b3a3a',
    secondary: '#c9a66b',
    accent: '#e3d5a8',
    background: '#faf7f0',
    surface: '#efe9da',
    text: '#2b1d15',
    muted: '#7c6753',
    border: '#d6ccb6',
    keywords: ['japanese', 'zen', 'japan', 'wabi', 'sabi', 'calm', 'meditative', 'quiet'],
    weight: 1.0,
  },
  'coffee-warm': {
    primary: '#6f4e37',
    secondary: '#a67b5b',
    accent: '#d4a574',
    background: '#fbf7f0',
    surface: '#f0e4d0',
    text: '#2a1a0d',
    muted: '#7a5a42',
    border: '#d9c4a3',
    keywords: ['coffee', 'warm', 'mocha', 'espresso', 'cafe', 'latte', 'brown', 'cozy'],
    weight: 1.0,
  },
  'emerald-fresh': {
    primary: '#10b981',
    secondary: '#34d399',
    accent: '#6ee7b7',
    background: '#ffffff',
    surface: '#ecfdf5',
    text: '#064e3b',
    muted: '#4a7867',
    border: '#d1fae5',
    keywords: ['emerald', 'fresh', 'green', 'spring', 'growth', 'vibrant', 'mint'],
    weight: 1.0,
  },
  'crimson-bold': {
    primary: '#dc143c',
    secondary: '#b31b3c',
    accent: '#ff4d6d',
    background: '#ffffff',
    surface: '#fff0f3',
    text: '#2a0612',
    muted: '#7a4252',
    border: '#f7c5cf',
    keywords: ['crimson', 'bold', 'red', 'passion', 'strong', 'dramatic', 'power'],
    weight: 1.0,
  },
  'slate-professional': {
    primary: '#334155',
    secondary: '#64748b',
    accent: '#94a3b8',
    background: '#ffffff',
    surface: '#f1f5f9',
    text: '#0f172a',
    muted: '#475569',
    border: '#cbd5e1',
    keywords: ['slate', 'professional', 'gray', 'business', 'serious', 'enterprise', 'corporate'],
    weight: 1.0,
  },
  'mint-fresh': {
    primary: '#14b8a6',
    secondary: '#5eead4',
    accent: '#99f6e4',
    background: '#ffffff',
    surface: '#f0fdfa',
    text: '#134e4a',
    muted: '#4a7a75',
    border: '#ccfbf1',
    keywords: ['mint', 'fresh', 'teal', 'cool', 'clean', 'refreshing', 'crisp'],
    weight: 1.0,
  },
  'mustard-vintage': {
    primary: '#c9a227',
    secondary: '#8b6f15',
    accent: '#e8cf6e',
    background: '#fbf7e8',
    surface: '#f2ebcb',
    text: '#2b2008',
    muted: '#827037',
    border: '#e0d6a3',
    keywords: ['mustard', 'vintage', 'retro', 'yellow', 'mid-century', 'nostalgic', 'old'],
    weight: 1.0,
  },
  'plum-sophisticated': {
    primary: '#5c2a50',
    secondary: '#8e4773',
    accent: '#c48ca8',
    background: '#fcfaff',
    surface: '#f3e8f0',
    text: '#2a0f27',
    muted: '#7a5670',
    border: '#e4cfdd',
    keywords: ['plum', 'sophisticated', 'wine', 'deep', 'rich', 'burgundy', 'refined'],
    weight: 1.0,
  },
  'charcoal-editorial': {
    primary: '#e4b23c',
    secondary: '#c9c9c9',
    accent: '#f5f5f5',
    background: '#1a1a1a',
    surface: '#262626',
    text: '#f0f0f0',
    muted: '#9a9a9a',
    border: '#383838',
    keywords: ['charcoal', 'editorial', 'dark', 'magazine', 'moody', 'elegant', 'premium'],
    weight: 1.0,
    dark: true,
  },
  'bubblegum-playful': {
    primary: '#ff70a6',
    secondary: '#ffd670',
    accent: '#70d6ff',
    background: '#ffffff',
    surface: '#fff4f9',
    text: '#3a0f25',
    muted: '#8a5a72',
    border: '#ffd6e4',
    keywords: ['bubblegum', 'playful', 'pink', 'fun', 'kids', 'cheerful', 'sweet', 'bright'],
    weight: 1.0,
  },

  // ── Hue-driven expansions ──
  'purple-royal': {
    primary: '#5b21b6',
    secondary: '#7c3aed',
    accent: '#a78bfa',
    background: '#ffffff',
    surface: '#f5f3ff',
    text: '#1e1033',
    muted: '#6d5a8a',
    border: '#ddd3f5',
    keywords: ['purple', 'royal', 'regal', 'deep', 'rich', 'majestic', 'violet'],
    weight: 1.0,
  },
  'purple-lavender': {
    primary: '#9f7aea',
    secondary: '#b794f4',
    accent: '#e9d8fd',
    background: '#fdfaff',
    surface: '#f6f0fd',
    text: '#2d1b55',
    muted: '#7a6a99',
    border: '#e3d6f5',
    keywords: ['purple', 'lavender', 'light', 'airy', 'soft', 'floral', 'spring'],
    weight: 1.0,
  },
  'pink-rose': {
    primary: '#e11d48',
    secondary: '#f43f5e',
    accent: '#fb7185',
    background: '#ffffff',
    surface: '#fff1f4',
    text: '#2d0714',
    muted: '#8a4455',
    border: '#ffd9e0',
    keywords: ['pink', 'rose', 'blush', 'romantic', 'warm', 'feminine'],
    weight: 1.0,
  },
  'pink-fuchsia': {
    primary: '#c026d3',
    secondary: '#e879f9',
    accent: '#f0abfc',
    background: '#ffffff',
    surface: '#fdf4ff',
    text: '#3a0c45',
    muted: '#8a4a9a',
    border: '#f4d6fb',
    keywords: ['pink', 'fuchsia', 'magenta', 'vibrant', 'bold', 'bright'],
    weight: 1.0,
  },
  'cyan-teal': {
    primary: '#0e7490',
    secondary: '#0891b2',
    accent: '#22d3ee',
    background: '#ffffff',
    surface: '#ecfeff',
    text: '#0a2a33',
    muted: '#4a7080',
    border: '#c7eff5',
    keywords: ['cyan', 'teal', 'aqua', 'ocean', 'tropical', 'water'],
    weight: 1.0,
  },
  'cyan-arctic': {
    primary: '#67e8f9',
    secondary: '#a5f3fc',
    accent: '#cffafe',
    background: '#060f14',
    surface: '#0c1a22',
    text: '#e0f7fb',
    muted: '#7a9aa5',
    border: '#1a323f',
    keywords: ['cyan', 'arctic', 'ice', 'frost', 'glacial', 'cold', 'dark'],
    weight: 1.0,
    dark: true,
  },
  'indigo-trust': {
    primary: '#4338ca',
    secondary: '#6366f1',
    accent: '#818cf8',
    background: '#ffffff',
    surface: '#eef2ff',
    text: '#0f1035',
    muted: '#545884',
    border: '#d1d6f8',
    keywords: ['indigo', 'trust', 'stable', 'professional', 'reliable', 'corporate'],
    weight: 1.0,
  },
  'indigo-night': {
    primary: '#a5b4fc',
    secondary: '#818cf8',
    accent: '#c7d2fe',
    background: '#0a0d1f',
    surface: '#141830',
    text: '#e6eafc',
    muted: '#7d83a8',
    border: '#252a4a',
    keywords: ['indigo', 'night', 'deep', 'cosmic', 'dark', 'space', 'dream'],
    weight: 1.0,
    dark: true,
  },
  'amber-harvest': {
    primary: '#b45309',
    secondary: '#d97706',
    accent: '#fbbf24',
    background: '#fffbeb',
    surface: '#fef3c7',
    text: '#2a1806',
    muted: '#7a5a2a',
    border: '#fde68a',
    keywords: ['amber', 'harvest', 'autumn', 'fall', 'warm', 'golden', 'rustic'],
    weight: 1.0,
  },
  'amber-copper': {
    primary: '#b45309',
    secondary: '#c2410c',
    accent: '#ea580c',
    background: '#fffaf2',
    surface: '#ffedd5',
    text: '#2b1405',
    muted: '#7a4a20',
    border: '#fed7aa',
    keywords: ['amber', 'copper', 'metallic', 'rust', 'warm', 'industrial'],
    weight: 1.0,
  },
  'orange-citrus': {
    primary: '#ea580c',
    secondary: '#fb923c',
    accent: '#fdba74',
    background: '#ffffff',
    surface: '#fff7ed',
    text: '#431407',
    muted: '#8a4920',
    border: '#fed7aa',
    keywords: ['orange', 'citrus', 'fresh', 'zest', 'bright', 'vibrant', 'tangy'],
    weight: 1.0,
  },
  'orange-terracotta': {
    primary: '#c2410c',
    secondary: '#9a3412',
    accent: '#e36414',
    background: '#fbf5ef',
    surface: '#f2e1cc',
    text: '#3a1606',
    muted: '#8a5030',
    border: '#d9be9c',
    keywords: ['orange', 'terracotta', 'clay', 'rustic', 'mediterranean', 'earthy', 'warm'],
    weight: 1.0,
  },

  // ── Industry vertical ──
  'healthcare-clean': {
    primary: '#0891b2',
    secondary: '#06b6d4',
    accent: '#67e8f9',
    background: '#ffffff',
    surface: '#f0f9ff',
    text: '#0c4a6e',
    muted: '#5a8090',
    border: '#bae6fd',
    keywords: ['healthcare', 'clean', 'medical', 'hospital', 'sterile', 'health', 'wellness', 'care'],
    weight: 1.0,
  },
  'legal-professional': {
    primary: '#1e3a8a',
    secondary: '#1e40af',
    accent: '#c0a062',
    background: '#fafafa',
    surface: '#f1f5f9',
    text: '#0a1230',
    muted: '#475569',
    border: '#cbd5e1',
    keywords: ['legal', 'professional', 'law', 'court', 'firm', 'authoritative', 'serious'],
    weight: 1.0,
  },
  'education-playful': {
    primary: '#f59e0b',
    secondary: '#2563eb',
    accent: '#ec4899',
    background: '#ffffff',
    surface: '#fff7ed',
    text: '#1e1b4b',
    muted: '#64748b',
    border: '#fde68a',
    keywords: ['education', 'playful', 'school', 'learning', 'kids', 'classroom', 'teaching'],
    weight: 1.0,
  },
  'saas-modern': {
    primary: '#6366f1',
    secondary: '#8b5cf6',
    accent: '#06b6d4',
    background: '#ffffff',
    surface: '#f8fafc',
    text: '#0f172a',
    muted: '#64748b',
    border: '#e2e8f0',
    keywords: ['saas', 'modern', 'software', 'app', 'startup', 'product', 'cloud'],
    weight: 1.0,
  },
  'enterprise-trust': {
    primary: '#0f766e',
    secondary: '#1e40af',
    accent: '#0891b2',
    background: '#ffffff',
    surface: '#f1f5f9',
    text: '#0f172a',
    muted: '#475569',
    border: '#cbd5e1',
    keywords: ['enterprise', 'trust', 'business', 'b2b', 'corporate', 'stable', 'reliable'],
    weight: 1.0,
  },
  'gaming-neon': {
    primary: '#a855f7',
    secondary: '#22d3ee',
    accent: '#facc15',
    background: '#08050f',
    surface: '#12082a',
    text: '#f0eaff',
    muted: '#8a7aa5',
    border: '#2a1a4a',
    keywords: ['gaming', 'neon', 'game', 'esports', 'arcade', 'rgb', 'electric'],
    weight: 1.0,
    dark: true,
  },
  'ecommerce-warm': {
    primary: '#dc2626',
    secondary: '#ea580c',
    accent: '#facc15',
    background: '#ffffff',
    surface: '#fff7ed',
    text: '#1a0808',
    muted: '#64748b',
    border: '#fed7aa',
    keywords: ['ecommerce', 'warm', 'shop', 'retail', 'store', 'commerce', 'shopping'],
    weight: 1.0,
  },
  'news-editorial': {
    primary: '#991b1b',
    secondary: '#1f2937',
    accent: '#f59e0b',
    background: '#fdfcfa',
    surface: '#f4f2ed',
    text: '#111111',
    muted: '#4b5563',
    border: '#d6d3cc',
    keywords: ['news', 'editorial', 'journalism', 'newspaper', 'media', 'press', 'article'],
    weight: 1.0,
  },
  'travel-breeze': {
    primary: '#0ea5e9',
    secondary: '#06b6d4',
    accent: '#f97316',
    background: '#ffffff',
    surface: '#f0f9ff',
    text: '#0c233b',
    muted: '#5b7b93',
    border: '#bae6fd',
    keywords: ['travel', 'breeze', 'vacation', 'tourism', 'sky', 'adventure', 'journey'],
    weight: 1.0,
  },
  'food-appetite': {
    primary: '#dc2626',
    secondary: '#f59e0b',
    accent: '#84cc16',
    background: '#fffaf2',
    surface: '#fef3c7',
    text: '#2b0c0c',
    muted: '#7a4a30',
    border: '#fed7aa',
    keywords: ['food', 'appetite', 'restaurant', 'cuisine', 'hungry', 'delicious', 'fresh'],
    weight: 1.0,
  },
  'banking-secure': {
    primary: '#064e3b',
    secondary: '#065f46',
    accent: '#f59e0b',
    background: '#ffffff',
    surface: '#f1f5f9',
    text: '#082028',
    muted: '#4b5563',
    border: '#d1d5db',
    keywords: ['banking', 'secure', 'bank', 'finance', 'wealth', 'vault', 'money'],
    weight: 1.0,
  },
  'creative-bold': {
    primary: '#f43f5e',
    secondary: '#8b5cf6',
    accent: '#facc15',
    background: '#ffffff',
    surface: '#fdf4ff',
    text: '#1a0a2e',
    muted: '#6b7280',
    border: '#e9d5ff',
    keywords: ['creative', 'bold', 'art', 'design', 'studio', 'agency', 'inspiring'],
    weight: 1.0,
  },

  // ── Brand moods / themes ──
  'minimalist-mono': {
    primary: '#000000',
    secondary: '#333333',
    accent: '#666666',
    background: '#ffffff',
    surface: '#fafafa',
    text: '#000000',
    muted: '#737373',
    border: '#e5e5e5',
    keywords: ['minimalist', 'mono', 'monochrome', 'minimal', 'simple', 'essential', 'pure'],
    weight: 1.0,
  },
  'brutalist-stark': {
    primary: '#ff0000',
    secondary: '#000000',
    accent: '#ffff00',
    background: '#ffffff',
    surface: '#f0f0f0',
    text: '#000000',
    muted: '#555555',
    border: '#000000',
    keywords: ['brutalist', 'stark', 'raw', 'harsh', 'bold', 'unpolished', 'concrete'],
    weight: 1.0,
  },
  'retro-80s': {
    primary: '#ff006e',
    secondary: '#8338ec',
    accent: '#3a86ff',
    background: '#0b0517',
    surface: '#1a0d2e',
    text: '#ffe5f0',
    muted: '#a06a90',
    border: '#3a1a50',
    keywords: ['retro', '80s', 'eighties', 'synthwave', 'neon', 'miami', 'nostalgic'],
    weight: 1.0,
    dark: true,
  },
  'vaporwave': {
    primary: '#ff77ff',
    secondary: '#77fffa',
    accent: '#ffce00',
    background: '#1a0933',
    surface: '#2a0f4c',
    text: '#ffe0ff',
    muted: '#a070c0',
    border: '#4a1a6a',
    keywords: ['vaporwave', 'aesthetic', 'retro', 'dream', 'pink', 'neon', 'surreal'],
    weight: 1.0,
    dark: true,
  },
  'solarized-light': {
    primary: '#268bd2',
    secondary: '#2aa198',
    accent: '#cb4b16',
    background: '#fdf6e3',
    surface: '#eee8d5',
    text: '#073642',
    muted: '#657b83',
    border: '#d8d2c2',
    keywords: ['solarized', 'light', 'code', 'editor', 'readable', 'dev'],
    weight: 1.0,
  },
  'solarized-dark': {
    primary: '#268bd2',
    secondary: '#2aa198',
    accent: '#b58900',
    background: '#002b36',
    surface: '#073642',
    text: '#fdf6e3',
    muted: '#839496',
    border: '#0a4854',
    keywords: ['solarized', 'dark', 'code', 'editor', 'terminal', 'dev'],
    weight: 1.0,
    dark: true,
  },
  'dracula-dark': {
    primary: '#bd93f9',
    secondary: '#ff79c6',
    accent: '#50fa7b',
    background: '#282a36',
    surface: '#44475a',
    text: '#f8f8f2',
    muted: '#6272a4',
    border: '#3b3d50',
    keywords: ['dracula', 'dark', 'vampire', 'purple', 'code', 'editor', 'ide'],
    weight: 1.0,
    dark: true,
  },
  'nord-cool': {
    primary: '#88c0d0',
    secondary: '#81a1c1',
    accent: '#a3be8c',
    background: '#2e3440',
    surface: '#3b4252',
    text: '#eceff4',
    muted: '#d8dee9',
    border: '#434c5e',
    keywords: ['nord', 'cool', 'nordic', 'arctic', 'frost', 'dev', 'editor'],
    weight: 1.0,
    dark: true,
  },
  'gruvbox-warm': {
    primary: '#d79921',
    secondary: '#b57614',
    accent: '#98971a',
    background: '#282828',
    surface: '#3c3836',
    text: '#ebdbb2',
    muted: '#928374',
    border: '#504945',
    keywords: ['gruvbox', 'warm', 'retro', 'earthy', 'dev', 'editor', 'vintage'],
    weight: 1.0,
    dark: true,
  },
  'tokyo-night': {
    primary: '#7aa2f7',
    secondary: '#bb9af7',
    accent: '#7dcfff',
    background: '#1a1b26',
    surface: '#24283b',
    text: '#c0caf5',
    muted: '#565f89',
    border: '#2f334d',
    keywords: ['tokyo', 'night', 'dark', 'code', 'editor', 'city', 'japan'],
    weight: 1.0,
    dark: true,
  },
  'monokai-contrast': {
    primary: '#f92672',
    secondary: '#a6e22e',
    accent: '#fd971f',
    background: '#272822',
    surface: '#3e3d32',
    text: '#f8f8f2',
    muted: '#75715e',
    border: '#49483e',
    keywords: ['monokai', 'contrast', 'code', 'editor', 'dev', 'classic', 'vibrant'],
    weight: 1.0,
    dark: true,
  },

  // ── Accessibility-first ──
  'high-contrast-light': {
    primary: '#000000',
    secondary: '#0000aa',
    accent: '#aa0000',
    background: '#ffffff',
    surface: '#f5f5f5',
    text: '#000000',
    muted: '#262626',
    border: '#000000',
    keywords: ['high-contrast', 'light', 'accessibility', 'a11y', 'wcag', 'readable', 'aaa'],
    weight: 1.0,
  },
  'high-contrast-dark': {
    primary: '#ffffff',
    secondary: '#ffff00',
    accent: '#00ffff',
    background: '#000000',
    surface: '#0a0a0a',
    text: '#ffffff',
    muted: '#d4d4d4',
    border: '#ffffff',
    keywords: ['high-contrast', 'dark', 'accessibility', 'a11y', 'wcag', 'aaa'],
    weight: 1.0,
    dark: true,
  },
  'deuteranopia-safe': {
    primary: '#0072b2',
    secondary: '#e69f00',
    accent: '#56b4e9',
    background: '#ffffff',
    surface: '#f1f5f9',
    text: '#0a1a2a',
    muted: '#475569',
    border: '#cbd5e1',
    keywords: ['deuteranopia', 'safe', 'colorblind', 'cb-safe', 'accessibility', 'okabe-ito'],
    weight: 1.0,
  },
  'protanopia-safe': {
    primary: '#0072b2',
    secondary: '#f0e442',
    accent: '#009e73',
    background: '#ffffff',
    surface: '#f5f5f5',
    text: '#111111',
    muted: '#525252',
    border: '#d4d4d4',
    keywords: ['protanopia', 'safe', 'colorblind', 'cb-safe', 'accessibility', 'red-blind'],
    weight: 1.0,
  },
  'tritanopia-safe': {
    primary: '#d55e00',
    secondary: '#cc79a7',
    accent: '#009e73',
    background: '#ffffff',
    surface: '#f5f5f5',
    text: '#111111',
    muted: '#525252',
    border: '#d4d4d4',
    keywords: ['tritanopia', 'safe', 'colorblind', 'cb-safe', 'accessibility', 'blue-blind'],
    weight: 1.0,
  },
  'low-light-reader': {
    primary: '#c0a062',
    secondary: '#a68a4e',
    accent: '#e4c888',
    background: '#15110a',
    surface: '#221c12',
    text: '#e8ddc4',
    muted: '#968468',
    border: '#2e2618',
    keywords: ['low-light', 'reader', 'night', 'reading', 'sepia', 'eye-strain', 'comfort'],
    weight: 1.0,
    dark: true,
  },
  'bright-outdoor': {
    primary: '#0b3d91',
    secondary: '#0a5caa',
    accent: '#ff6d00',
    background: '#ffffff',
    surface: '#f5f5f5',
    text: '#000000',
    muted: '#363636',
    border: '#a3a3a3',
    keywords: ['bright', 'outdoor', 'daylight', 'sunny', 'glare', 'outside', 'hdr'],
    weight: 1.0,
  },
};

export const PALETTE_COUNT = Object.keys(PALETTES).length;
